src/Api.js, src/App.css
=> add error message for slippage

src/Exchange.css, src/components/Exchange/PositionsList.js
=> show error order inside position list

src/Shared.css, src/components/Exchange/SwapBox.js
for eth max button sets value to balance - margin for gas
=> fix locked confirmation state

src/views/Stake/StakeV2.js
=> fix ens error by removing unnecessary request

src/components/EventToast/useEventToast.js, src/config/events.js
Add `validTill` to the announcement toast message. Only announcements in future will be visible.
=> add validTill to the announcement toast

src/views/Stake/StakeV2.js
=> refactor the text and logic for reserved amount

src/Helpers.js, src/components/Exchange/ConfirmationBox.js, src/components/Exchange/OrderEditor.js, src/components/Exchange/OrdersList.js, src/components/Exchange/PositionEditor.js, src/components/Exchange/PositionSeller.js, src/components/Exchange/PositionsList.js, src/components/Exchange/SwapBox.js, src/components/Exchange/TradeHistory.js, src/views/Exchange/Exchange.js, src/views/Stake/StakeV2.js
=> Trade fixes

src/components/Common/SEO.js
Small change to fix SEO site name
Fixes issue #120
=> Change SEO site name to GMX

src/Helpers.js, src/views/Stake/StakeV2.js
=> show gmx apr including boosted by MPs

src/App.js, src/Footer.css, src/Footer.js, src/Shared.css, src/views/Home/Home.css, src/views/ReferralTerms/ReferralTerms.css, src/views/ReferralTerms/ReferralTerms.js
[x] Add referral terms page
[x] Add the link to the footer
=> add referral terms page and link to footer

src/App.css, src/App.js, src/Helpers.js, src/components/Glp/GlpSwap.js, src/views/Dashboard/AssetDropdown.css, src/views/Dashboard/AssetDropdown.js, src/views/Dashboard/DashboardV2.css, src/views/Dashboard/DashboardV2.js
=> add token image to dashboard

src/App.js, src/components/Referrals/TradersStats.js
[x] Remove referral code from url when the code is added to `localStorage`
[x] Fix an edge case when for referral data not available
=> replace params when ref in localstorage

src/Api/index.js, src/components/Exchange/TradeHistory.js, src/views/Exchange/Exchange.js
=> Show No trades yet when user is not connected on Trades tab

src/components/Exchange/OrdersList.js
=> add collateral to the order list

src/App.js, src/views/Referrals/Referrals.js
support url like https://app.gmx.io/#/referrals/0xffffffffffffffffffff00000000000000000000
=> support account param in url for referrals page

src/App.js, src/components/Glp/GlpSwap.js, src/hooks/useScrollToTop.js, src/hooks/useScrollZero.js, src/views/Buy/Buy.js, src/views/BuyGMX/BuyGMX.js, src/views/Exchange/Exchange.js, src/views/ReferralTerms/ReferralTerms.js, src/views/Stake/StakeV2.js, src/views/TermsAndConditions/TermsAndConditions.js
=> Refactor scroll 0 0

src/components/Exchange/OrdersList.js
Fix order type on OrderList component
=> fix: order type on order list

src/components/Exchange/PositionsList.js, src/views/Exchange/Exchange.css
1. Screen getting black on clicking close when the order is waiting to be opened.
2. Fix the scroll bar on mobile. It was very close to the body.
=> fix blank screen on clicking close

src/App.js, src/Footer.css, src/Footer.js, src/Helpers.js, src/components/ModalViews/RedirectModal.css, src/views/Home/Home.js
=> Fix jobs link

src/components/ModalViews/RedirectModal.css
=> fix checkbox alignment for redirect modal

src/App.css, src/hooks/useTotalVolume.js, src/views/Dashboard/DashboardV2.js, src/views/Dashboard/TooltipCard.js
=> Dashboard total volume

src/Footer.js, src/views/Jobs/Jobs.js
=> remove active job

.gitignore, src/Helpers.js, src/components/Exchange/ConfirmationBox.js, src/components/Exchange/PositionSeller.css, src/components/Exchange/PositionSeller.js, src/components/Exchange/PositionsList.js, src/components/Exchange/SwapBox.css, src/components/Exchange/SwapBox.js, src/components/Exchange/TokenSelector.css, src/components/Exchange/TokenSelector.js, src/components/Modal/Modal.js, src/components/Tooltip/Tooltip.js, src/components/Tooltip/TooltipWithPortal.js, src/hooks/useLockBodyScroll.js, src/utils/constants.js, src/views/Exchange/Exchange.js
Task: https://app.asana.com/0/1201404209663627/1201719254714513/f
Pr preview for "not enough liquidity case" https://github.com/gmx-io/gmx-interface/pull/240
=> Receive token change feature

src/App.css, src/App.js, src/components/NetworkDropdown/LanguagePopupHome.js, src/components/NetworkDropdown/NetworkDropdown.css
- Fix home page header responsive
=> update responsive on header home

src/components/Exchange/SwapBox.js, src/views/Stake/StakeV2.js
Fix WalletWallet to Wallet
Fix the Insufficient liquidity and modal name message on button
=> update translated message

src/Helpers.js, src/components/Exchange/PositionEditor.js, src/components/Exchange/PositionSeller.js, src/components/Exchange/SwapBox.js, src/components/Glp/GlpSwap.js, src/components/Tab/Tab.js, src/config/events.js, src/locales/en/messages.js, src/locales/en/messages.po, src/locales/es/messages.js, src/locales/es/messages.po, src/locales/fr/messages.js, src/locales/fr/messages.po, src/locales/ja/messages.js, src/locales/ja/messages.po, src/locales/ko/messages.js, src/locales/ko/messages.po, src/locales/ru/messages.js, src/locales/ru/messages.po, src/locales/zh/messages.js, src/locales/zh/messages.po
Add network disabled state for GLP buy, sell, swap and leverage trade
=> Add network disabled

src/components/Exchange/PositionSeller.js, src/config/locales/en/messages.js, src/config/locales/en/messages.po, src/config/locales/es/messages.js, src/config/locales/es/messages.po, src/config/locales/fr/messages.js, src/config/locales/fr/messages.po, src/config/locales/ja/messages.js, src/config/locales/ja/messages.po, src/config/locales/ko/messages.js, src/config/locales/ko/messages.po, src/config/locales/ru/messages.js, src/config/locales/ru/messages.po, src/config/locales/zh/messages.js, src/config/locales/zh/messages.po
https://app.asana.com/0/1201404209663627/1202881629558381/f
1. Added bufferAmount checks for targetToken
2. disabled max out checks for Wrap/Unwrap
3. Added collateral symbol to the modal as @xhiroz  requested
=> Fix min pool amount

src/components/Header/AppHeaderLinks.tsx
[x] Remove redirect popup when you click on mobile logo
[x] Remove home form mobile drawer
=> remove home from mobile menu and redirect popup

src/components/BuyInputSection/BuyInputSection.js, src/components/Common/SEO.js, src/components/Glp/GlpSwap.js, src/components/InputSection/InputSection.js
=> signed commit for #270

src/components/Exchange/TradeHistory.js, src/components/Glp/SwapErrorModal.tsx, src/config/locales/en/messages.po, src/config/locales/es/messages.po, src/config/locales/fr/messages.po, src/config/locales/ja/messages.po, src/config/locales/ko/messages.po, src/config/locales/ru/messages.po, src/config/locales/zh/messages.po, src/pages/Stake/StakeV2.js
[x] Fix glp buy no liquidity text
[x] Update tooltip style on trades tab and actions page.
---
- https://app.asana.com/0/0/1203044677077616
=> update glp buy text and tooltip style

src/components/Exchange/NoLiquidityErrorModal.tsx, src/components/Exchange/PositionsList.js, src/components/Exchange/SwapBox.js, src/config/chains.ts, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po, src/pages/Exchange/Exchange.css, src/styles/Shared.css
[x] Add edit icon to collateral on the position list. Clicking on which will open the Deposit/Withdraw modal
[x] Change tooltip text
[x] Change default collateral on avalanche to USDC from MIM
[x] Change error message from `Profits In` to `Collateral In`
---
- https://app.asana.com/0/0/1203125312342900
- https://app.asana.com/0/0/1203101482911686
=> add icon and change tooltip text for collateral

src/components/EventToast/EventToast.js, src/components/NetworkDropdown/LanguagePopupHome.js, src/config/events.ts
[x] Add norush trading contest
[x] Update event toast to accept multiple sentences
=> add norush contest announcement

src/config/tokens.ts, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po, src/pages/Dashboard/AssetDropdown.tsx
[x] Add proof of reserves to GLP
---
- https://app.asana.com/0/0/1203331741290808
=> Proof of reserve

src/components/Exchange/PositionSeller.js
[x] Show stable asset for short trigger orders.
[x] Show no value when trigger price is not added
---
- https://app.asana.com/0/0/1203247464865844
=> fix showing stable for short trigger orders

src/components/Glp/GlpSwap.js, src/components/Stake/GMXAprTooltip.tsx, src/components/StatsTooltip/StatsTooltipRow.tsx, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po, src/pages/Stake/StakeV2.js
[x] Update GLP Swap to use `managedAmount` instead of `poolAmount`
---
- https://app.asana.com/0/0/1203247464865849
- https://app.asana.com/0/0/1203199570847028
=> update poolAmount to managedAmount on glpswap

src/App/App.js
[x] Change pollingInterval to 2000. By default it was 4000.
---
- https://app.asana.com/0/0/1203222378802935
=> change pollingInterval for avax to 2000

package.json
Changed no-console rule to warn, to allow project compile locally
=> No console warn

src/config/events.ts
[x] Remove AVAX Rush announcement
=> remove avax rush announcement

src/components/Exchange/OrdersList.js, src/components/Exchange/PositionsList.js, src/pages/Actions/Actions.js
Hide the following on /actions page
[x] Hide checkbox on order list 
[x] Hide tooltip
[x] Hide edit collateral on position list
[x] Hide three dots
---
- https://app.asana.com/0/0/1203320114215159
=> hide user actions on actions page

src/components/Header/Header.tsx, src/components/Header/HomeHeaderLinks.tsx, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po
[x] Add app to home menu
---
- https://app.asana.com/0/0/1203393191055373
=> add app to home menu

src/components/Common/ConnectWalletButton.scss, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po
[x] Add active and hover state to Connect Button
---
- https://app.asana.com/0/0/1203486074494122
=> add hover and active state to connect button

src/lib/contracts/transactionErrors.ts
https://app.asana.com/0/1201404209663627/1203393191055344/f
=> Add "we can't execute this request" to RPC error notification

src/components/Exchange/ExchangeTVChart.js
[x] Filter assets to show for chart positions
---
- https://app.asana.com/0/0/1203592334171373
=> show chart position of only related positions

src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po, src/pages/Ecosystem/Ecosystem.js
[x] Add PlutusDAO, GMX Swap, Position Manager, Beefy and few others to ecosystem
---
- https://app.asana.com/0/0/1203586627903979
=> Add multiple projects to Ecosystem page

src/components/Exchange/ConfirmationBox.js, src/components/Exchange/PositionEditor.js, src/components/Exchange/PositionSeller.js, src/components/Exchange/PositionsList.js, src/components/Exchange/TradeHistory.js, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po, src/pages/Actions/Actions.css
[x] Update tooltip fees message
[x] Add line break on net value tooltip on PositionList
---
- https://app.asana.com/0/0/1203486074494149
=> update tooltip messgae for fees

src/pages/BeginAccountTransfer/BeginAccountTransfer.js
[x] Fix error in console for making request when account is not active
---
- https://app.asana.com/0/0/1203777627855648
=> add check for active account

src/lib/wallets/index.tsx
[x] Make setSelectedProvider on ethereum object optional
---
- https://app.asana.com/0/0/1203801220464369
=> update to have setSelectedProvider optional

netlify.toml, public/tradingview-chart.css, src/components/TVChartContainer/TVChartContainer.tsx, src/components/TVChartContainer/constants.ts, src/config/tokens.ts, src/domain/tradingview/requests.ts, src/domain/tradingview/useTVDatafeed.ts, src/lib/dates.ts
[x] Implement Tradingview Full
---
- https://app.asana.com/0/0/1201266503318581
=> Refactor tradingview

src/components/Exchange/TradeHistory.css, src/components/Exchange/TradeHistory.js, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po, src/pages/BuyGMX/constants.ts
[x] Fix list of centralised exchanges for buy GMX 
---
- https://app.asana.com/0/0/1203850634694417
- https://app.asana.com/0/0/1203850634694409
- https://app.asana.com/0/0/1203851354727769
- https://app.asana.com/0/0/1203851354727774
=> add avax for centralised exchanges

public/tradingview-chart.css, src/components/Exchange/ExchangeTVChart.js, src/components/TVChartContainer/TVChartContainer.tsx, src/components/TVChartContainer/constants.ts, src/domain/prices.ts, src/domain/tradingview/TVDataProvider.ts, src/domain/tradingview/requests.ts, src/domain/tradingview/types.ts, src/domain/tradingview/useTVDatafeed.ts, src/domain/tradingview/utils.ts, src/lib/localStorage/index.ts
[x] Add loading indicator
[x] Cache requested data so it doesn't need to fetch multiple times
[x] Update few UI issues
---
- https://app.asana.com/0/0/1203632258598534
=> Update tradingview ux

public/tradingview-chart.css, src/components/Exchange/ExchangeTVChart.js, src/components/TVChartContainer/TVChartContainer.tsx, src/components/TVChartContainer/constants.ts, src/domain/tradingview/TVDataProvider.ts, src/domain/tradingview/requests.ts, src/domain/tradingview/types.ts, src/domain/tradingview/useTVDatafeed.ts, src/domain/tradingview/utils.ts
---
- https://app.asana.com/0/0/1203632258598534
- https://app.asana.com/0/0/1204093549564163
=> [WIP] Update Charts to sync data without reloading

src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po, src/pages/Stake/StakeV2.css, src/pages/Stake/StakeV2.js
[x] Fix button alignments on Earn page
---
- https://app.asana.com/0/0/1204191337065131
=> fix button alignments

src/App/App.js, src/domain/tokens/useInfoTokens.ts, src/pages/Stats/Stats.css, src/pages/Stats/Stats.tsx
**Do not merge**
---
- https://app.asana.com/0/0/1204210635151879
=> add page with token stats

src/domain/tradingview/TVDataProvider.ts, src/domain/tradingview/requests.ts
=> fix stable coin pricing

netlify.toml
---
- https://app.asana.com/0/0/1204422509259512
=> remove X-XSS-Protection

src/domain/legacy.ts, src/pages/Exchange/Exchange.js
---
- https://app.asana.com/0/0/1204422509259569
=> update arbitrum execution fee

src/components/Exchange/PositionSeller.css, src/components/Exchange/TokenSelector.css
[x] Fix receive modal scroll on bigger screen
---
- https://app.asana.com/0/0/1204422509259534
=> fix receive scroll

src/components/Exchange/ConfirmationBox.js, src/components/Exchange/FeesTooltip.tsx, src/components/Exchange/PositionEditor.js, src/components/Exchange/PositionSeller.js, src/components/Exchange/SwapBox.js, src/components/Glp/GlpSwap.js, src/config/chains.ts, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po
[x] Replace fees tooltip on swap box
[x] Handle press enter to submit order
---
- https://app.asana.com/0/0/1204379579274821
=> Enter to order

src/components/BuyInputSection/BuyInputSection.js, src/components/Exchange/SwapBox.js
[x] Input input number issue for GLP buy/sell
---
- https://app.asana.com/0/0/1204494514180058
=> add step to input

src/components/Exchange/PositionsList.js
[x] Fix screen going blank while position close modal is open and changing the wallet.
---
- https://app.asana.com/0/0/1204514065446132
=> show modal only when position exists

src/config/contracts.ts, src/pages/ReferralsTier/ReferralsTier.tsx
---
- https://app.asana.com/0/0/1204595882901580
=> fix referrals tier page

src/components/Synthetics/ConfirmationBox/ConfirmationBox.tsx, src/components/Synthetics/MarketCard/MarketCard.tsx, src/components/Synthetics/OrderItem/OrderItem.tsx, src/components/Synthetics/PositionItem/PositionItem.tsx, src/components/Synthetics/PositionSeller/PositionSeller.tsx, src/components/Synthetics/SwapCard/SwapCard.tsx, src/components/Synthetics/TVChart/TVChart.tsx, src/components/Synthetics/TradeBox/TradeBox.tsx, src/components/Synthetics/TradeFeesRow/TradeFeesRow.tsx, src/components/Synthetics/TradeHistoryRow/TradeHistoryRow.tsx, src/config/tokens.ts, src/domain/tokens/types.ts, src/domain/tradingview/useTVDatafeed.ts, src/pages/SyntheticsPage/SyntheticsPage.tsx
[x] Support variable price decimals for tokens
=> Fix price decimals synths

src/components/Synthetics/PositionItem/PositionItem.tsx, src/components/Synthetics/TradeBox/TradeBox.tsx
[x] Fix price decimals for limit orders and orders on position list
=> fix price decimals

src/components/Exchange/PositionDropdown.css, src/components/Exchange/PositionDropdown.js, src/components/Synthetics/ConfirmationBox/ConfirmationBox.tsx, src/components/Synthetics/PositionItem/PositionItem.tsx, src/components/Synthetics/PositionList/PositionList.tsx, src/components/Synthetics/PositionSeller/PositionSeller.tsx, src/domain/synthetics/trade/useSelectedTradeOption.ts, src/pages/SyntheticsPage/SyntheticsPage.tsx
[x] Add new options to position dropdown
=> add new options to position dropdown

src/components/Exchange/PositionDropdown.js, src/components/Synthetics/MarketStats/MarketStats.scss, src/components/Synthetics/MarketStats/MarketStats.tsx, src/components/Synthetics/PositionEditor/PositionEditor.scss, src/components/Synthetics/PositionEditor/PositionEditor.tsx, src/components/Synthetics/PositionItem/PositionItem.tsx, src/components/Tooltip/Tooltip.css, src/pages/MarketPoolsPage/MarketPoolsPage.tsx
[x] increase tootltip min width
[x] fix spacings
[x] Add footer to pools
[x] Mobile optimize pools card
=> style changes

src/components/Referrals/AffiliatesStats.js, src/config/subgraph.ts, src/domain/referrals/index.ts, src/domain/referrals/useReferralsData.ts
---
- https://app.asana.com/0/0/1204647982362943
=> migrate subgraphs to Satsuma

src/App/App.js, src/components/Synthetics/PositionItem/PositionItem.tsx, src/components/Synthetics/PositionList/PositionList.tsx, src/pages/MarketPoolsPage/MarketPoolsPage.tsx, src/pages/SyntheticsPage/SyntheticsPage.tsx
=> update pnl on positionlist

src/components/Synthetics/ConfirmationBox/ConfirmationBox.tsx, src/components/Synthetics/GmList/GmList.tsx, src/components/Synthetics/GmSwap/GmConfirmationBox/GmConfirmationBox.tsx, src/components/Synthetics/GmSwap/GmSwapBox/GmSwapBox.tsx, src/components/Synthetics/MarketStats/MarketStats.tsx, src/components/Synthetics/OrderList/OrderList.tsx, src/components/Synthetics/PositionSeller/PositionSeller.tsx, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po
[x] Add separator for "I am aware of" and "Approve (TOKEN)"
=> add modal divider

src/domain/referrals/index.ts
[x] Change user affiliate code query based on the new schema
=> refactor refferer to affiliate

src/components/Common/SEO.js, src/lib/legacy.ts, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po, src/pages/Buy/Buy.js, src/pages/Dashboard/DashboardV2.js, src/pages/Ecosystem/Ecosystem.js, src/pages/Exchange/Exchange.js, src/pages/Jobs/Jobs.js, src/pages/PageNotFound/PageNotFound.js, src/pages/ReferralTerms/ReferralTerms.js, src/pages/Referrals/Referrals.js, src/pages/Stake/StakeV2.js, src/pages/TermsAndConditions/TermsAndConditions.js
[x] Add SEO metatags to translation
[x] Update trade page title
---
- https://app.asana.com/0/0/1204448366277735
=> add metatags to translation

public/index.html
[x] Add og info to index.html
---
- https://app.asana.com/0/0/1204334997212042
=> update the og info on index.html

src/components/EventToast/EventToast.js, src/config/chains.ts, src/config/events.ts, src/config/tokens.ts
[x] Change USDC to USDC.e
---
- https://app.asana.com/0/0/1203645069388997
=> change usdc to usdc.e

src/lib/numbers.ts, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po
[x] Add min and max threshold to number formats
---
- https://app.asana.com/0/0/1204173577512419
=> add threshold numbers

src/components/StatsTooltip/StatsTooltipRow.tsx, src/components/Synthetics/MarketsList/MarketsList.tsx
[x] Change Pool to Pools Value
[x] Show max valued pool funding rate
---
- https://app.asana.com/0/0/1203201806700734
=> update v2 pools

src/components/Exchange/PositionSeller.js, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po
[x] Update position close validation check
---
- https://app.asana.com/0/0/1204911431110695
=> Fix full close validation

src/App/App.js
[x] Add websocket for avalanche
---
- https://app.asana.com/0/0/1204964735615348
=> add websocket for avax

src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po, src/pages/Ecosystem/Ecosystem.css, src/pages/Ecosystem/Ecosystem.js
[x] Add new ecosystem projects
[x] Change two to three columns layout
---
- https://app.asana.com/0/0/1204847614307731
=> add ecosystem projects

src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po, src/pages/CompleteAccountTransfer/CompleteAccountTransfer.js
[x] Validate the sender and receiver addresses
---
- https://app.asana.com/0/0/1204866389962550
=> validate the receiver and sender addresses

src/components/Exchange/ExchangeTVChart.js, src/components/MarketSelector/MarketSelector.scss, src/components/Modal/Modal.css, src/components/Synthetics/TVChart/TVChart.tsx, src/components/TVChartContainer/TVChartContainer.tsx, src/components/TokenSelector/TokenSelector.css, src/domain/tradingview/TVDataProvider.ts, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po
=> fix chart and modal

src/components/TVChartContainer/TVChartContainer.tsx
[x] Chart current price to support price decimals
=> add support for price decimals

src/App/App.scss, src/pages/Home/Home.css, src/pages/Referrals/Referrals.css
[x] Remove border form cards
---
- https://app.asana.com/0/0/1204804284562374
=> remove border from app-card

src/App/App.js, src/components/EventToast/EventToast.js, src/components/ExternalLink/ExternalLink.tsx, src/components/MarketSelector/MarketSelector.tsx, src/components/MarketSelector/PoolSelector.tsx, src/components/Synthetics/GmSwap/GmSwapBox/GmSwapBox.tsx, src/components/Synthetics/PositionEditor/PositionEditor.tsx, src/components/Synthetics/TradeBox/TradeBox.tsx, src/components/Synthetics/TradeHistoryRow/LiquidationTooltip.tsx, src/components/TokenCard/TokenCard.js, src/config/events.ts, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po
[x] Add "Use V2" to event notification
[x] Add comma to balances on input
---
- https://app.asana.com/0/0/1205190912643259
- https://app.asana.com/0/0/1205214479766001
- https://app.asana.com/0/0/1205214479766008
=> update announcement and add comma

src/components/ShareBar/ShareBar.scss, src/domain/synthetics/markets/utils.ts, src/pages/SyntheticsStats/SyntheticsStats.tsx
---
- https://app.asana.com/0/0/1205172761500153
=> Fix swap liquidity

src/components/Synthetics/ConfirmationBox/ConfirmationBox.tsx, src/components/Synthetics/GmSwap/GmConfirmationBox/GmConfirmationBox.tsx, src/components/Synthetics/GmSwap/GmSwapBox/GmSwapBox.tsx, src/components/Synthetics/TradeBox/TradeBox.tsx, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po
[x] Add enter to order
---
- https://app.asana.com/0/0/1205190911952176
=> add enter to order for v2

src/pages/Dashboard/DashboardV2.js
[x] Add v2 stats to dashboard
---
- https://app.asana.com/0/0/1205276763751758
=> add v2 stats

src/domain/synthetics/trade/utils/decrease.ts
---
- https://app.asana.com/0/0/1205227545469349
=> Fix full close receive amount

src/domain/synthetics/positions/usePositions.ts
[x] Fix positions not loading for v2 actions
---
- https://app.asana.com/0/0/1205214717764684
=> fix position not loading on actions

src/components/Synthetics/OrderItem/OrderItem.tsx, src/components/Synthetics/OrderList/OrderList.tsx, src/components/Synthetics/PositionItem/PositionItem.scss, src/components/Synthetics/PositionItem/PositionItem.tsx, src/domain/synthetics/orders/utils.ts, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po
[x] Add invalid trigger order errors
---
- https://app.asana.com/0/0/1204569399453542
=> invalid trigger order for orders

src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po, src/pages/Ecosystem/Ecosystem.js
[x] Add unidex leverage
---
- https://app.asana.com/0/0/1205267756409568
=> add unidex

src/components/Exchange/PositionEditor.js, src/components/Exchange/SwapBox.js, src/components/Glp/GlpSwap.js, src/components/Synthetics/GmSwap/GmSwapBox/GmSwapBox.tsx, src/components/Synthetics/PositionEditor/PositionEditor.tsx, src/components/Synthetics/TradeBox/TradeBox.tsx, src/config/ui.ts, src/lib/wallets/useIsMetamaskMobile.ts, src/pages/Stake/StakeV2.js
[x] Limit decimals to 5 for token approval on Metamask mobile
---
- https://app.asana.com/0/0/1205227545469345
=> limit decimals on metamask mobile

src/components/Exchange/PositionsList.js, src/components/Exchange/SwapBox.js, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po, src/pages/Exchange/Exchange.css, src/pages/Exchange/Exchange.js, src/styles/Shared.css
[x] Add warning for short collateral change
---
- https://app.asana.com/0/0/1204886452330318
=> add warning for collateral change

src/components/MarketSelector/PoolSelector.tsx
[x] Fix repeating search icon on pool selector
---
- https://app.asana.com/0/0/1205325998522877
=> fix search pool icon

src/pages/BuyGMX/BuyGMX.tsx
[x] Change BondProtocol link
---
- https://app.asana.com/0/0/1205325998522872
=> update bond protocol link

src/components/Exchange/ChartTokenSelector.scss, src/components/Exchange/ExchangeTVChart.js, src/components/Synthetics/TVChart/TVChart.scss, src/components/Synthetics/TVChart/TVChart.tsx, src/components/Synthetics/TradeBox/TradeBox.tsx, src/components/VersionSwitch/VersionSwitch.scss, src/components/VersionSwitch/VersionSwitch.tsx, src/pages/Exchange/Exchange.css
[x] Update version switcher
---
- https://app.asana.com/0/0/1205299402070477
- https://app.asana.com/0/0/1205325998522992
=> update version switcher

src/domain/synthetics/tokens/useOracleKeeperFetcher.ts
---
- https://app.asana.com/0/0/1205366869751530
=> fix weth candles

src/components/Exchange/ExchangeTVChart.js, src/components/Synthetics/TVChart/TVChart.tsx, src/components/TVChartContainer/SaveLoadAdapter.ts, src/components/TVChartContainer/TVChartContainer.tsx
[x] Fix save load chart for v1 and v2
---
- https://app.asana.com/0/0/1205101390585875
=> save save and load to have app version

src/domain/tokens/utils.ts
---
- https://app.asana.com/0/0/1205366869751543
=> Fix BTC equality check

src/components/Synthetics/TradeHistoryRow/helpers.spec.ts, src/components/Synthetics/TradeHistoryRow/helpers.ts, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po
---
- https://app.asana.com/0/0/1205553229159114
=> Trade actions for v2 fixes

src/App/App.scss, src/components/Exchange/PositionsList.js, src/components/Synthetics/PositionItem/PositionItem.tsx, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po, src/pages/Exchange/Exchange.css
---
- https://app.asana.com/0/0/1205276763751798
=> remove selecting market from prices cols, remove opening settings from leverage

src/components/Synthetics/PositionSeller/PositionSeller.tsx, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po, src/pages/SyntheticsPage/SyntheticsPage.tsx
---
- https://app.asana.com/0/0/1205202214516096
=> Trigger tab in close order modal

src/domain/synthetics/markets/createDepositTxn.ts, src/domain/synthetics/markets/createWithdrawalTxn.ts, src/domain/synthetics/orders/createDecreaseOrderTxn.ts, src/domain/synthetics/orders/createIncreaseOrderTxn.ts, src/domain/synthetics/orders/createSwapOrderTxn.ts, src/domain/synthetics/orders/simulateExecuteOrderTxn.tsx, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po
Reverts gmx-io/gmx-interface#609
=> Revert "Fix simulations"

src/App/App.js
[x] Fix path comparison to matchPath
---
- https://app.asana.com/0/0/1205647817031782
=> fix path match

src/components/StatsTooltip/StatsTooltip.css, src/components/Tooltip/Tooltip.scss, src/components/Tooltip/TooltipWithPortal.tsx, src/pages/SyntheticsStats/SyntheticsStats.scss, src/pages/SyntheticsStats/SyntheticsStats.tsx
[x] Change v2 stats style
---
- https://app.asana.com/0/0/1205567396592786
=> fix v2 stats style

src/App/App.js, src/lib/useTradeRedirect.ts, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po
=> fix loop issue

src/domain/referrals/hooks/index.ts, src/domain/referrals/utils.ts, src/domain/synthetics/positions/usePositionsInfo.ts, src/pages/SyntheticsActions/SyntheticsActions.tsx
[x] Fix local referral code for actions
---
- https://app.asana.com/0/0/1205526066891632
=> fix local referral code for actions

src/App/App.scss, src/components/Exchange/FeesTooltip.tsx, src/components/Referrals/ReferralInfoCard.tsx, src/components/Referrals/TradersStats.scss, src/components/Referrals/TradersStats.tsx, src/components/StatsTooltip/StatsTooltip.css, src/components/Synthetics/GmList/GmList.scss, src/components/Synthetics/GmSwap/GmFees/GmFees.scss, src/components/Synthetics/MarketStats/MarketStats.scss, src/components/Synthetics/TradeFeesRow/TradeFeesRow.scss, src/components/Synthetics/TradeFeesRow/TradeFeesRow.tsx, src/components/Tooltip/Tooltip.scss, src/domain/referrals/hooks/useReferralsData.ts, src/domain/referrals/types.ts, src/domain/referrals/useReferralsData.ts, src/domain/synthetics/claimHistory/useClaimHistory.ts, src/pages/Dashboard/DashboardV2.css, src/pages/Exchange/Exchange.css, src/pages/Referrals/Referrals.css
[x] Fix tooltip on mobile
---
- https://app.asana.com/0/0/1205772624092389
=> fix tooltip for mobile

src/components/Referrals/AddAffiliateCode.js, src/components/Synthetics/ConfirmationBox/ConfirmationBox.tsx, src/components/Synthetics/TradeBox/CollateralSelectorRow.tsx, src/components/Synthetics/TradeBox/TradeBox.tsx, src/domain/synthetics/orders/utils.ts, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po, src/pages/Exchange/Exchange.css, src/pages/Referrals/Referrals.css
[x] Update order warnings
---
- https://app.asana.com/0/0/1205674902656090
=> add live order warnings

src/components/EventToast/useEventToast.js, src/components/Synthetics/MarketCard/MarketCard.tsx, src/config/dataStore.ts, src/config/events.ts, src/domain/synthetics/markets/types.ts, src/domain/synthetics/markets/useMarketsInfo.ts, src/domain/synthetics/testUtils/mocks.ts, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po
[x] Add adaptive funding fee to market card
[x] Show adaptive funding fee to notification
=> add adaptive funding fee

src/components/EventToast/useEventToast.js, src/config/events.ts
[x] Add network support for Event Notification
[x] Add async conditions support 
---
- https://app.asana.com/0/0/1205829384721401
=> Add async notification

src/components/Synthetics/GmSwap/GmConfirmationBox/GmConfirmationBox.tsx, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po
[x] Fix GM token allowance error
=> fix token allowance

src/components/AprInfo/AprInfo.tsx, src/components/Glp/GlpSwap.js, src/components/TokenCard/TokenCard.js, src/config/events.ts, src/domain/synthetics/fees/utils/index.ts, src/domain/synthetics/tokens/useOracleKeeperFetcher.ts, src/lib/numbers.ts, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po, src/pages/BuyGlp/BuyGlp.css, src/pages/BuyGlp/BuyGlp.js
[x] Add GLP to GM migration info
---
- https://app.asana.com/0/0/1205829386512416
=> Add incentive info

src/components/Synthetics/MarketCard/MarketCard.tsx, src/components/Synthetics/MarketsList/MarketsList.tsx, src/components/Synthetics/TradeHistoryRow/mocks.ts, src/config/dataStore.ts, src/domain/synthetics/markets/types.ts, src/domain/synthetics/markets/useMarketsInfo.ts, src/domain/synthetics/markets/utils.ts, src/domain/synthetics/testUtils/mocks.ts, src/pages/SyntheticsStats/SyntheticsStats.tsx
[x] Add MAX_OPEN_INTEREST
---
- https://app.asana.com/0/0/1205877859617801
=> Add max open interest

src/components/Synthetics/MarketsList/MarketsList.tsx, src/domain/synthetics/markets/utils.ts, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po
[x] Update utilization logic
---
- https://app.asana.com/0/0/1205947643086409
=> update utilization logic

src/locales/fr/messages.po
[x] Remove unwanted text from fr translation
---
- https://app.asana.com/0/0/1205567531909039
=> remove unwanted text form fr translation

src/App/App.js, src/components/Synthetics/TradeFeesRow/TradeFeesRow.tsx, src/components/TokenCard/TokenCard.js, src/domain/synthetics/stats/useV2Stats.ts, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po, src/pages/Dashboard/DashboardV2.js, src/pages/Home/Home.js
[x] Add v2 stats to total volume, open interest and users on homepage
---
- https://app.asana.com/0/0/1205956665105562
- https://app.asana.com/0/0/1205907108876736
- https://app.asana.com/0/0/1206009702800064
=> Add gm to home

src/config/ui.ts, src/domain/synthetics/fees/utils/useUiFeeFactor.ts, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po
=> fix ui fee receiver

src/lib/wallets/WalletProvider.tsx
[x] Add zerion and okx wallet
---
- https://app.asana.com/0/0/1206048236386632
- https://app.asana.com/0/0/1205907106989444
=> add okx and zerion

src/components/Tooltip/Tooltip.tsx, src/components/Tooltip/TooltipWithPortal.tsx, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po
[x] Fix tooltip hover with anchor tag
---
- https://app.asana.com/0/0/1206030056691133
=> fix tooltip open with link on mobile

src/config/events.ts
=> add ledger msg

src/components/Synthetics/PositionItem/PositionItem.tsx, src/pages/Exchange/Exchange.css
=> fix tooltip position

src/components/PercentageInput/PercentageInput.scss
---
- https://app.asana.com/0/0/1206208151115805
=> fix acceptable price input

src/components/Synthetics/TradeBox/TradeBox.tsx, src/domain/synthetics/trade/utils/validation.ts, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po
---
- https://app.asana.com/0/0/1206189396973355
=> calculate dynamic minCollateralFactor to validate leverage

src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po, src/pages/Dashboard/DashboardV2.js
---
- https://app.asana.com/0/0/1206048236386572
=> rename to treasury

src/components/Synthetics/OrderEditor/OrderEditor.tsx
[x] Fix Acceptable Price on Edit Order
---
- https://app.asana.com/0/0/1205559447051843
=> Fix acceptable price edit modal

src/components/Synthetics/PositionItem/PositionItem.tsx
---
- https://app.asana.com/0/0/1206189396973366
=> fix mobile position order warnings

src/components/Synthetics/OrderEditor/OrderEditor.tsx
---
- https://app.asana.com/0/0/1206213175632296
=> fix swap order edit

src/components/Synthetics/OrderEditor/OrderEditor.tsx, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po
---
- https://app.asana.com/0/0/1205270170884374
=> add leverage checks while editing order

src/App/App.scss, src/components/Exchange/ConfirmationBox.js, src/components/Synthetics/ConfirmationBox/ConfirmationBox.tsx, src/components/Synthetics/OrderEditor/OrderEditor.tsx, src/components/Synthetics/PositionEditor/PositionEditor.tsx, src/components/Synthetics/PositionSeller/PositionSeller.tsx, src/components/Synthetics/TradeBox/TradeBox.tsx, src/components/ValueTransition/ValueTransition.tsx, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po
---
- https://app.asana.com/0/0/1206301908736222
=> Standardize labels ordering

src/components/Exchange/SwapBox.js, src/components/LeverageSlider/LeverageSlider.tsx, src/components/Synthetics/TradeBox/TradeBox.tsx, src/config/ui.ts, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po
---
- https://app.asana.com/0/0/1206092706230183
=> update leverage marks

package.json, src/components/Exchange/SwapBox.js, src/components/Synthetics/Claims/Claims.tsx, src/components/Synthetics/ConfirmationBox/ConfirmationBox.tsx, src/components/Synthetics/GmList/GmList.tsx, src/components/Synthetics/OrderEditor/OrderEditor.tsx, src/components/Synthetics/TradeBox/TradeBox.tsx, src/context/SyntheticsStateContext/hooks/tradeHooks.ts, src/context/SyntheticsStateContext/hooks/tradeboxHooks.ts, src/context/SyntheticsStateContext/selectors/tradeSelectors.ts, src/context/SyntheticsStateContext/selectors/tradeboxSelectors.ts, src/context/SyntheticsStateContext/utils.ts, src/domain/synthetics/claimHistory/useClaimHistory.ts, yarn.lock
---
- https://app.asana.com/0/0/1206489279455640
- https://app.asana.com/0/0/1206489279455652
- https://app.asana.com/0/0/1206489279455624
- https://app.asana.com/0/0/1206489279455630
- https://app.asana.com/0/0/1206489279455648
- https://app.asana.com/0/0/1206489279455644
=> Refactoring fixes

src/components/Exchange/ExchangeInfoRow.js, src/pages/Exchange/Exchange.css
---
- https://app.asana.com/0/0/1206513187657223
=> fix pnl alignment

src/components/LeverageSlider/LeverageSlider.tsx, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po, src/pages/Exchange/Exchange.css
[x] Fix slide when dropped on iframe (chart) it keeps dragging
---
- https://app.asana.com/0/0/1204545702859373
=> fix slide keeps dragging after dropped on iframe

src/context/SyntheticsStateContext/SyntheticsStateContextProvider.tsx, src/context/SyntheticsStateContext/hooks/globalsHooks.ts, src/pages/SyntheticsActions/SyntheticsActions.tsx
---
- https://app.asana.com/0/0/1206556806689367
=> fix actions page (used current account)

src/components/Synthetics/PositionSeller/PositionSeller.tsx, src/components/ValueTransition/ValueTransition.scss, src/components/ValueTransition/ValueTransition.tsx
---
- https://app.asana.com/0/0/1206513187657223
=> fix label alignment

src/components/Synthetics/TradeHistoryRow/utils.spec.ts, src/components/Synthetics/TradeHistoryRow/utils.ts
---
- https://app.asana.com/0/0/1205165966968528
=> fix swap orders price

src/components/TokenCard/TokenCard.tsx, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po, src/pages/Buy/Buy.tsx
---
- https://app.asana.com/0/0/1206048236386579
=> misc: buy page texts

src/domain/synthetics/orders/utils.ts, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po
---
- https://app.asana.com/0/0/1206276578148394
=> misc: edit order warning translations

src/App/App.js, src/App/App.scss, src/components/SettingsModal/SettingsModal.scss, src/components/SettingsModal/SettingsModal.tsx, src/components/Synthetics/ConfirmationBox/ConfirmationBox.tsx, src/components/Synthetics/ConfirmationBox/rows/AllowedSlippageRow.tsx, src/components/Synthetics/MarketCard/MarketCard.tsx, src/components/Synthetics/PositionSeller/PositionSeller.tsx, src/components/Synthetics/PositionSeller/rows/AllowedSlippageRow.tsx, src/context/SettingsContext/SettingsContextProvider.tsx, src/lib/localStorage/index.ts, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po
---
- https://app.asana.com/0/0/1206188451069134
=> fix: add minus to allw. slip.

src/pages/Exchange/Exchange.css
---
- https://app.asana.com/0/0/1206558806096451
=> fix: safari values misplacement

src/App/App.js, src/App/App.scss, src/components/SettingsModal/SettingsModal.scss, src/components/SettingsModal/SettingsModal.tsx, src/components/Synthetics/ConfirmationBox/ConfirmationBox.tsx, src/components/Synthetics/ConfirmationBox/rows/AllowedSlippageRow.tsx, src/components/Synthetics/MarketCard/MarketCard.tsx, src/components/Synthetics/PositionSeller/PositionSeller.tsx, src/components/Synthetics/PositionSeller/rows/AllowedSlippageRow.tsx, src/context/SettingsContext/SettingsContextProvider.tsx, src/lib/localStorage/index.ts, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po
---
- https://app.asana.com/0/0/1206188451069134
=> Allwd slppg minuses

src/config/ui.ts
---
- https://app.asana.com/0/0/1206599100243838
=> update tooltip open delay

src/components/Exchange/ConfirmationBox.js, src/components/Exchange/PositionSeller.js, src/components/PercentageInput/PercentageInput.scss, src/components/PercentageInput/PercentageInput.tsx, src/components/Synthetics/AcceptablePriceImpactInputRow/AcceptablePriceImpactInputRow.tsx, src/components/Synthetics/ConfirmationBox/ConfirmationBox.tsx, src/components/Synthetics/ConfirmationBox/rows/AllowedSlippageRow.tsx, src/components/Synthetics/OrderEditor/OrderEditor.tsx, src/components/Synthetics/PositionSeller/PositionSeller.tsx, src/components/Synthetics/PositionSeller/rows/AllowedSlippageRow.tsx, src/components/Synthetics/TradeBox/TradeBox.tsx, src/components/Tooltip/TooltipWithPortal.tsx, src/domain/synthetics/orders/index.ts, src/domain/synthetics/orders/updateOrderTxn.ts, src/domain/synthetics/trade/useTradeState.ts
---
- https://app.asana.com/0/0/1205425393876832
=> feat: edit order acceptable price impact

src/components/Exchange/ExchangeInfo.tsx, src/components/Synthetics/ConfirmationBox/ConfirmationBox.tsx, src/components/Synthetics/GmSwap/GmSwapBox/GmSwapBox.tsx, src/components/Synthetics/PositionEditor/PositionEditor.tsx, src/components/Synthetics/PositionSeller/PositionSeller.tsx, src/components/Synthetics/TradeBox/TradeBox.tsx
---
- https://app.asana.com/0/0/1206597205824097
=> Exchange info groups refactoring

src/components/Synthetics/OrderItem/OrderItem.tsx
---
- https://app.asana.com/0/0/1206646357917636
=> Fix collateral symbol

src/components/Synthetics/ConfirmationBox/ConfirmationBox.tsx, src/components/Synthetics/OrderEditor/OrderEditor.tsx, src/components/Synthetics/PositionEditor/PositionEditor.tsx, src/components/Synthetics/PositionSeller/PositionSeller.tsx, src/domain/synthetics/orders/createDecreaseOrderTxn.ts, src/domain/synthetics/orders/createIncreaseOrderTxn.ts, src/domain/synthetics/orders/createSwapOrderTxn.ts, src/domain/synthetics/orders/updateOrderTxn.ts, src/lib/contracts/callContract.tsx, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po
---
- https://app.asana.com/0/0/1206558806097499
=> reduce subaccount lag

src/components/Exchange/ExchangeInfoRow.tsx, src/components/Synthetics/ConfirmationBox/ConfirmationBox.tsx, src/components/Synthetics/GmSwap/GmConfirmationBox/GmConfirmationBox.tsx, src/components/Synthetics/GmSwap/GmFees/GmFees.tsx, src/components/Synthetics/GmSwap/GmSwapBox/GmSwapBox.tsx, src/components/Synthetics/NetworkFeeRow/NetworkFeeRow.scss, src/components/Synthetics/NetworkFeeRow/NetworkFeeRow.tsx, src/components/Synthetics/PositionEditor/PositionEditor.tsx, src/components/Synthetics/PositionSeller/PositionSeller.tsx, src/components/Synthetics/TradeBox/TradeBox.tsx, src/components/Synthetics/TradeFeesRow/TradeFeesRow.tsx, src/domain/synthetics/fees/utils/executionFee.ts, src/lib/numbers.ts, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po
Resolves https://app.asana.com/0/1206524620304500/1206646232564900
=> Tradebox network fee

src/components/Synthetics/ChartTokenSelector/ChartTokenSelector.scss, src/components/Synthetics/MarketTokenSelector/MarketTokenSelector.scss
---
- https://app.asana.com/0/0/1206736505163402
=> Update max-height in ChartTokenSelector and MarketTokenSelector

src/domain/synthetics/leaderboard/constants.ts, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po, src/pages/LeaderboardPage/components/LeaderboardContainer.tsx
=> add competitions rules link

src/App/App.js, src/components/Footer/Footer.tsx, src/components/Header/HeaderLink.tsx, src/components/TokenCard/TokenCard.tsx, src/lib/legacy.ts
---
- https://app.asana.com/0/0/1206777951596280
=> Refactor redirectPopupTimestamp serialization and deserialization

src/components/Button/Button.tsx, src/components/Checkbox/Checkbox.tsx, src/components/Exchange/PositionEditor.js, src/components/Exchange/PositionSeller.js, src/components/GmTokensBalanceInfo/GmTokensBalanceInfo.tsx, src/components/SettingsModal/SettingsModal.tsx, src/components/Synthetics/GmList/GmList.tsx, src/components/Synthetics/OrderEditor/OrderEditor.tsx, src/components/Synthetics/OrderItem/OrderItem.tsx, src/components/Synthetics/OrderList/OrderList.tsx, src/components/Synthetics/PositionEditor/PositionEditor.tsx, src/components/Synthetics/PositionItem/PositionItem.tsx, src/components/Synthetics/PositionSeller/PositionSeller.tsx, src/components/Tooltip/Tooltip.scss, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po, src/pages/Exchange/Exchange.css, src/pages/Stake/StakeV2.js
---
- https://app.asana.com/0/0/1205533073029219
- https://app.asana.com/0/0/1205325998522892
- https://app.asana.com/0/0/1206188451069160
- https://app.asana.com/0/0/1206750633765284
- https://app.asana.com/0/0/1206399503398509
- https://app.asana.com/0/0/1206626863771244
- https://app.asana.com/0/0/1206147108533527
- https://app.asana.com/0/0/1206188451069172
=> Fix UI related issues

src/config/bridging.ts
---
- https://app.asana.com/0/0/1206779029469456
=> Fis aave to have tokens

src/components/APRLabel/APRLabel.js, src/components/Stake/GMXAprTooltip.tsx, src/components/TokenCard/TokenCard.tsx, src/domain/rewards/useStakedBnGMXAmount.ts, src/lib/legacy.ts, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po, src/pages/Stake/StakeV2.js
---
- https://app.asana.com/0/0/1206819293733495
=> Fix avg apr buy

src/pages/Exchange/Exchange.css
---
- https://app.asana.com/0/0/1206539765950955
=> Adjust left position of Exchange list item indicator

src/components/Exchange/FeesTooltip.tsx, src/components/Exchange/SwapBox.js, src/components/SubaccountNavigationButton/SubaccountNavigationButton.tsx, src/components/Synthetics/MarketCard/MarketCard.tsx, src/components/Synthetics/MarketStats/MarketStats.tsx, src/components/Synthetics/TradeBox/TradeBox.tsx, src/lib/contracts/transactionErrors.tsx, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po, src/pages/Dashboard/DashboardV2.js, src/pages/Stake/StakeV2.js
---
- https://app.asana.com/0/0/1206493430435438
=> Update link text to "Read more" in various files

src/components/Synthetics/GmSwap/GmConfirmationBox/GmConfirmationBox.tsx
---
- https://app.asana.com/0/0/1206301908736231
=> show gm name in allow

src/components/Header/Header.tsx, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po
---
- https://app.asana.com/0/0/1206915122037204
=> Fix competition link

src/components/Common/ConnectWalletButton.scss, src/components/Header/AppHeaderLinks.tsx, src/components/Header/AppHeaderUser.tsx, src/components/Header/Header.scss, src/components/Header/Header.tsx, src/components/Header/HeaderLink.tsx, src/components/Header/HomeHeaderLinks.tsx
1. Ellipsis on header links (when desktop)
2. nowrap on connect wallet button
---
- https://app.asana.com/0/0/1206558806096463
=> Fix header adapt width

src/components/EventToast/EventToast.css, src/components/EventToast/EventToast.tsx, src/components/EventToast/useEventToast.tsx, src/config/events.ts
---
- https://app.asana.com/0/0/1206915122197856
=> add binance campaign event

src/components/Synthetics/SettleAccruedFundingFeeModal/SettleAccruedFundingFeeModal.tsx
---
- https://app.asana.com/0/0/1206433495782415
=> Refactor SettleAccruedFundingFeeModal component

src/components/PageTitle/PageTitle.scss, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po, src/pages/Dashboard/DashboardV2.js
---
- https://app.asana.com/0/0/1206862808656401
=> update tokens info

src/components/MarketSelector/MarketSelector.tsx, src/components/MarketSelector/PoolSelector.tsx, src/components/Modal/Modal.tsx, src/components/Synthetics/MarketTokenSelector/MarketTokenSelector.tsx, src/components/TokenSelector/TokenSelector.tsx
now chevron hides only when nessessary
---
- https://app.asana.com/0/0/1206433988899249
=> Fix pool selector hidden chevron

src/components/Synthetics/TableOptionsFilter/TableOptionsFilter.tsx, src/components/Synthetics/TableOptionsFilter/groups.tsx, src/components/Synthetics/TradeHistory/TradeHistory.tsx, src/components/Synthetics/TradeHistory/useDownloadAsCsv.tsx, src/components/ToastifyDebug/ToastifyDebug.tsx, src/domain/synthetics/tradeHistory/useTradeHistory.ts, src/lib/csv.ts, src/lib/guards.ts, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po
---
- https://app.asana.com/0/0/1206862808656406
=> Increase trades history csv size up to 10_000

src/components/LeverageSlider/LeverageSlider.tsx, src/components/Synthetics/DateRangeSelect/DateRangeSelect.tsx, src/domain/synthetics/__tests__/markets/chooseSuitableMarket.spec.ts
---
- https://app.asana.com/0/0/1207018189091635
=> Fix react ref warnings and misc

src/lib/wallets/rainbowKitConfig.ts
---
- https://app.asana.com/0/0/1207092385792595
=> Refactor wallet list in rainbowKitConfig.ts

package.json, src/config/chains.ts
---
- https://app.asana.com/0/0/1207097968461800
=> update alchemy urls

src/charting_library.d.ts, src/components/Synthetics/TVChart/TVChart.tsx, src/config/subgraph.ts, src/domain/prices.ts, src/domain/synthetics/tokens/use24PriceDelta.ts, src/domain/synthetics/tokens/useOracleKeeperFetcher.ts, src/domain/synthetics/tokens/useTokenRecentPricesData.ts, src/domain/synthetics/tradingview/SyntheticsTVDataProvider.ts, src/domain/tradingview/TVDataProvider.ts, src/domain/tradingview/__tests__/fillBarGaps.spec.ts, src/domain/tradingview/__tests__/subscribeBars.spec.ts, src/domain/tradingview/requests.ts, src/domain/tradingview/types.ts, src/domain/tradingview/useTVDatafeed.ts, src/domain/tradingview/utils.ts
---
- https://app.asana.com/0/0/1205118053791993
=> Fix data TradingView data feed provider

package.json, src/components/AprInfo/AprInfo.tsx, src/components/Synthetics/GmList/GmList.tsx, src/components/Synthetics/MarketStats/MarketStats.tsx, src/components/TokenCard/TokenCard.tsx, src/config/chains.ts, src/config/subgraph.ts, src/domain/synthetics/leaderboard/index.ts, src/domain/synthetics/markets/useMarketTokensAPR.ts, src/domain/synthetics/markets/useMarketsInfoRequest.ts, src/domain/synthetics/markets/useUserEarnings.ts, src/lib/legacy.ts, src/lib/subgraph/clients.ts, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po, src/pages/MarketPoolsPage/MarketPoolsPage.tsx
---
- https://app.asana.com/0/0/1205674902656010
=> include pending borrowing fee in pools APR

src/lib/multicall/useMulticall.ts, src/lib/wallets/rainbowKitConfig.ts
---
- https://app.asana.com/0/0/1207154604243311
=> Fix flacky contract calls

src/components/Modal/Modal.tsx, src/domain/synthetics/trade/useTradeboxState.ts
---
- https://app.asana.com/0/0/1207178561398248
=> Fix tradebox state WIP

src/components/Stake/GMXAprTooltip.tsx, src/lib/legacy.ts, src/pages/Stake/StakeV2.tsx
---
- https://app.asana.com/0/0/1207178561398241
=> fix earn page crash

src/domain/synthetics/trade/useTradeboxState.ts
---
- https://app.asana.com/0/0/1207072227899598
=> fix toggling tokens in swap mode

src/components/Synthetics/OrderEditor/OrderEditor.tsx, src/components/Synthetics/TradeBox/TradeBox.tsx, src/config/factors.ts, src/config/ui.ts, src/context/SyntheticsStateContext/selectors/orderEditorSelectors.ts, src/context/SyntheticsStateContext/selectors/tradeboxSelectors/index.ts, src/domain/synthetics/markets/utils.ts, src/domain/synthetics/positions/usePositionsInfo.ts, src/domain/synthetics/trade/utils/validation.ts
---
- https://app.asana.com/0/0/1207267299939491
=> Dynamic Maximum Leverage instead of Static 50x

src/components/Synthetics/OrderEditor/OrderEditor.tsx, src/components/Synthetics/TradeBox/TradeBox.tsx, src/config/factors.ts, src/config/ui.ts, src/context/SyntheticsStateContext/selectors/orderEditorSelectors.ts, src/context/SyntheticsStateContext/selectors/tradeboxSelectors/index.ts, src/domain/synthetics/markets/utils.ts, src/domain/synthetics/positions/usePositionsInfo.ts, src/domain/synthetics/trade/utils/validation.ts
Reverts gmx-io/gmx-interface#946
=> Revert "Dynamic Maximum Leverage instead of Static 50x"

src/components/Synthetics/ConfirmationBox/ConfirmationBox.tsx
---
- https://app.asana.com/0/0/1207308828296860
=> fix 1ct native token warn cond

src/components/Synthetics/ConfirmationBox/ConfirmationBox.tsx
---
- https://app.asana.com/0/0/1207394804009017
=> fix sltp disabled button

src/components/Button/Button.tsx, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po, src/pages/BuyGMX/BuyGMX.tsx, src/pages/BuyGMX/constants.ts
---
- https://app.asana.com/0/0/1207432753332057
=> update buy gmx page

src/pages/BuyGMX/constants.ts
Resolves https://app.asana.com/0/1206524620304500/1207238281992715
=> Remove Binance Connect as a fiat gateway option

src/config/chains.ts, src/context/SubaccountContext/SubaccountContext.tsx, src/context/SyntheticsEvents/SyntheticsEventsProvider.tsx, src/domain/synthetics/orders/cancelOrdersTxn.ts, src/domain/synthetics/orders/createDecreaseOrderTxn.ts, src/domain/synthetics/orders/createIncreaseOrderTxn.ts, src/domain/synthetics/orders/createSwapOrderTxn.ts, src/domain/synthetics/orders/updateOrderTxn.ts, src/domain/synthetics/subaccount/withdrawFromSubaccount.ts, src/lib/contracts/callContract.tsx, src/lib/contracts/utils.ts, src/lib/wallets/useEthersSigner.ts
---
- https://app.asana.com/0/0/1207160644931224
=> 1ct rpc url from wallet

src/config/events.tsx
---
- https://app.asana.com/0/0/1207483353443939
=> new leverage announcement

src/pages/Stake/StakeV2.tsx
Resolves https://app.asana.com/0/1206524620304500/1207092385792587
=> Update VesterDepositModal to use nextReserveAmount for handle calculation

src/pages/BeginAccountTransfer/BeginAccountTransfer.tsx, src/pages/ClaimEsGmx/ClaimEsGmx.js, src/pages/CompleteAccountTransfer/CompleteAccountTransfer.js, src/pages/LeaderboardPage/LeaderboardPage.scss, src/pages/LeaderboardPage/components/CompetitionPrizes.tsx, src/pages/LeaderboardPage/components/LeaderboardContainer.tsx, src/pages/LeaderboardPage/components/LeaderboardNavigation.tsx, src/pages/OrdersOverview/OrdersOverview.css, src/pages/OrdersOverview/OrdersOverview.js, src/pages/PositionsOverview/PositionsOverview.css, src/pages/PositionsOverview/PositionsOverview.js, src/pages/ReferralsTier/ReferralsTier.scss, src/pages/ReferralsTier/ReferralsTier.tsx, src/pages/SyntheticsStats/SyntheticsStats.scss, src/pages/SyntheticsStats/SyntheticsStats.tsx, src/pages/UiPage/UiPage.tsx, src/styles/Shared.scss
Resolves https://app.asana.com/0/1206524620304500/1207018189091651
=> Update default container padding on mobile to 1rem

src/components/Synthetics/MarketStats/MarketStats.tsx, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po
Resolves https://app.asana.com/0/1206524620304500/1207154604243393
=> Edit APR and GM token price tooltips

src/App/App.scss, src/components/Synthetics/TradeHistory/useDownloadAsCsv.tsx, src/domain/synthetics/orders/simulateExecuteOrderTxn.tsx, src/lib/contracts/transactionErrors.tsx, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po
---
- https://app.asana.com/0/0/1207154604243319
=> handle more rpc errors

src/components/Synthetics/SubaccountModal/SubaccountModal.scss
---
- https://app.asana.com/0/0/1207517121878967
=> Fix subaccount icons

src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po, src/pages/Stake/StakeV2.tsx
Resolves https://app.asana.com/0/1206524620304500/1207238281992694
use revoke.cash to revoke to see such checkboxes
=> Earn approve spending checkboxes

src/lib/__tests__/getBestNonce.spec.ts, src/lib/contracts/callContract.tsx, src/lib/contracts/utils.ts
---
- https://app.asana.com/0/0/1207517313253443
=> 1ct best nonce

src/components/Synthetics/MarketTokenSelector/MarketTokenSelector.tsx
---
- https://app.asana.com/0/0/1207540770484275
=> APR -> APY in GM dropdown table's header

src/components/Synthetics/PositionSeller/PositionSeller.tsx, src/config/localStorage.ts, src/context/SyntheticsStateContext/selectors/positionSellerSelectors.ts, src/domain/synthetics/trade/usePositionSellerState.ts
---
- https://app.asana.com/0/0/1206895696287196
=> Persist receive token per market/pool/direction

src/components/Synthetics/PositionItem/PositionItem.tsx
Before:
After:
---
- https://app.asana.com/0/0/1207509401625004
=> Fix multi-order cards alignment mobile

src/styles/Shared.scss
---
- https://app.asana.com/0/0/1207483353443910
=> Fixed jumping UI on vertical scroll appearance

src/components/PercentageInput/PercentageInput.scss, src/components/PercentageInput/PercentageInput.tsx
---
- https://app.asana.com/0/0/1207558142130620
=> Fix pecentage suggest

src/components/Exchange/FeesTooltip.tsx, src/components/SettingsModal/SettingsModal.tsx, src/components/Synthetics/ConfirmationBox/ConfirmationBox.tsx, src/components/Synthetics/GmSwap/GmConfirmationBox/GmConfirmationBox.tsx, src/components/Synthetics/NetworkFeeRow/NetworkFeeRow.tsx, src/components/Synthetics/OrderEditor/OrderEditor.tsx, src/components/Synthetics/PositionEditor/PositionEditor.tsx, src/components/Synthetics/PositionSeller/PositionSeller.tsx, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po
---
- https://app.asana.com/0/0/1206895696287184
=> Renamed 'execution fee' to 'network fee'

src/components/Exchange/PositionEditor.js
---
- https://app.asana.com/0/0/1207432269012262
=> V1: fix withdraw collateral quick entry select

src/components/Button/Button.tsx, src/components/Synthetics/Claims/ClaimsHistory.tsx, src/components/Synthetics/DateRangeSelect/DateRangeSelect.tsx, src/components/Synthetics/TradeHistory/TradeHistory.tsx, src/pages/AccountDashboard/DailyAndCumulativePnL.tsx, src/pages/BuyGMX/BuyGMX.tsx
---
- https://app.asana.com/0/0/1207592788941890
=> improved Button's img usage

src/components/Synthetics/Claims/Claims.tsx, src/components/Synthetics/PositionItem/PositionItem.tsx, src/components/Synthetics/PositionList/PositionList.tsx, src/components/Synthetics/SettleAccruedFundingFeeModal/SettleAccruedFundingFeeModal.tsx, src/components/Synthetics/SettleAccruedFundingFeeModal/utils.ts, src/context/SyntheticsStateContext/hooks/globalsHooks.ts, src/context/SyntheticsStateContext/selectors/globalSelectors.ts, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po, src/pages/AccountDashboard/HistoricalLists.tsx, src/pages/SyntheticsPage/SyntheticsPage.tsx
---
- https://app.asana.com/0/0/1206916369835088
=> Pre-select settle funding fees

src/components/Exchange/TradeHistory.css
---
- https://app.asana.com/0/0/1207592788942005
=> fix font size

src/components/BuyInputSection/BuyInputSection.scss
---
- https://app.asana.com/0/0/1207623939533367
=> fix swap gap

src/lib/chains/useRealChainIdWarning.ts
Resolves https://app.asana.com/0/1206524620304500/1207585520326000
=> Add delay for invalid network notification

src/pages/BuyGMX/BuyGMX.tsx
---
- https://app.asana.com/0/0/1207638643826925
=> open gmx swap in a new tab

src/components/Exchange/PositionSeller.js, src/components/Synthetics/PositionSeller/PositionSeller.tsx, src/domain/synthetics/trade/usePositionSellerState.ts
---
- https://app.asana.com/0/0/1207592788941998
=> Fixed close token saving

src/components/AprInfo/AprInfo.tsx, src/components/Synthetics/GmList/GmList.tsx, src/components/Synthetics/MarketStats/MarketStats.tsx, src/components/Synthetics/TradeFeesRow/TradeFeesRow.tsx, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po
---
- https://app.asana.com/0/0/1207664262973211
=> add sparkle icon to gm pools list

src/components/StatsTooltip/StatsTooltipRow.tsx, src/components/Synthetics/ConfirmationBox/ConfirmationBox.tsx, src/components/Synthetics/ExecutionPriceRow.tsx, src/components/Synthetics/MarketCard/MarketCard.tsx, src/components/Synthetics/PositionSeller/PositionSeller.tsx, src/components/Synthetics/TradeBox/TradeBox.tsx, src/components/Synthetics/TradeFeesRow/TradeFeesRow.tsx, src/components/Tooltip/Tooltip.tsx, src/components/Tooltip/TooltipWithPortal.tsx, src/context/SyntheticsStateContext/selectors/positionSellerSelectors.ts, src/context/SyntheticsStateContext/selectors/tradeboxSelectors/index.ts, src/domain/synthetics/positions/utils.ts, src/domain/synthetics/trade/usePositionSellerState.ts, src/domain/synthetics/trade/utils/common.ts, src/domain/synthetics/trade/utils/decrease.ts, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po
---
- https://app.asana.com/0/0/1207483353443957
=> Separate execution price row

src/components/Exchange/PositionSeller.js, src/config/localStorage.ts, src/domain/synthetics/trade/usePositionSellerState.ts
---
- https://app.asana.com/0/0/1207638636058418
=> Save receive token respecting collateral token of position

src/domain/synthetics/orders/createDecreaseOrderTxn.ts, src/domain/synthetics/orders/createIncreaseOrderTxn.ts, src/domain/synthetics/orders/createSwapOrderTxn.ts
This reverts commit 130034bda5354beb4bca96f8abbcf487b12fb886.
=> Revert "fix new ref codes ReferralStorage revert"

src/components/Synthetics/SubaccountModal/SubaccountModal.scss, src/components/Synthetics/SubaccountModal/SubaccountModal.tsx, src/context/SubaccountContext/SubaccountContext.tsx, src/domain/synthetics/subaccount/withdrawFromSubaccount.ts, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po
---
- https://app.asana.com/0/0/1207589010234688
=> fix subaccount withdrawal

src/config/events.tsx
---
- https://app.asana.com/0/0/1207693542936316
=> single side avalanche market announcement

src/components/Synthetics/ConfirmationBox/ConfirmationBox.tsx, src/components/Synthetics/PositionSeller/PositionSeller.tsx, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po
---
- https://app.asana.com/0/0/1207610540953635
=> Disable simulation for tpsl

src/components/Synthetics/TradeHistory/TradeHistory.tsx, src/pages/AccountDashboard/HistoricalLists.tsx
---
- https://app.asana.com/0/0/1207664262973248
=> Remove PnL analysis link from dashboard

src/components/Synthetics/ClaimModal/ClaimModal.tsx
---
- https://app.asana.com/0/0/1207432268747537
=> fix token claim list

src/components/AprInfo/AprInfo.tsx, src/components/Banner/BannerButton.tsx, src/components/Glp/GlpSwap.js, src/components/Synthetics/TradeFeesRow/TradeFeesRow.tsx, src/components/Synthetics/UserIncentiveDistributionList/UserIncentiveDistributionList.tsx, src/components/TokenCard/TokenCard.tsx, src/config/events.tsx, src/config/links.ts, src/config/ui.ts, src/context/SyntheticsStateContext/selectors/globalSelectors.ts, src/domain/synthetics/common/useIncentiveStats.ts, src/domain/synthetics/markets/useGmMarketsApy.ts, src/domain/synthetics/tokens/useAirdroppedTokenTitle.tsx, src/domain/synthetics/tokens/useOracleKeeperFetcher.ts, src/lib/legacy.ts, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po, src/pages/BuyGlp/BuyGlp.js, src/pages/Stake/StakeV2.tsx
---
- https://app.asana.com/0/0/1207693543129561
=> Exclude some LPs liquidity from incentives apr calc

src/domain/synthetics/fees/utils/priceImpact.ts, src/domain/synthetics/trade/utils/deposit.ts, src/domain/synthetics/trade/utils/swapStats.ts
---
- https://app.asana.com/0/0/1207551082462897
=> support swap price impact changes in v2.1

src/components/Synthetics/GmList/GmList.tsx, src/components/Synthetics/MarketStats/MarketStats.tsx, src/context/SyntheticsEvents/SyntheticsEventsProvider.tsx, src/domain/synthetics/markets/utils.ts, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po
---
- https://app.asana.com/0/0/1207726302045459
=> fix displayed pool amounts

src/components/Synthetics/TradeBox/TradeBox.tsx, src/config/tokens.ts, src/domain/synthetics/trade/useTradeParamsProcessor.ts, src/domain/synthetics/trade/useTradeboxState.ts, src/pages/Exchange/Exchange.css
---
- https://app.asana.com/0/0/1207300395314351
=> tradebox switch logic update

src/components/Synthetics/SubaccountModal/SubaccountModal.tsx
---
- https://app.asana.com/0/0/1207615165314894
=> subaccount witdrawal loading

src/components/Synthetics/SubaccountModal/SubaccountModal.tsx, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po
---
- https://app.asana.com/0/0/1207674127595726
=> fix subaccount withdrawal text

src/components/Synthetics/TradeFeesRow/TradeFeesRow.tsx, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po
---
- https://app.asana.com/0/0/1207774544324688
=> Updated trade fees tooltip  

package.json, src/components/Synthetics/TradeBox/TradeBox.tsx, src/config/tokens.ts, src/domain/synthetics/trade/useTradeParamsProcessor.ts, src/domain/synthetics/trade/useTradeboxState.ts, src/pages/Exchange/Exchange.css, yarn.lock
---
- https://app.asana.com/0/0/1207300395314351
=> Tradebox switch logic update v2

src/components/Synthetics/ConfirmationBox/ConfirmationBox.tsx, src/components/Synthetics/ConfirmationBox/SideOrderEntries.tsx, src/context/SyntheticsStateContext/selectors/sidecarOrdersSelectors.ts, src/domain/synthetics/sidecarOrders/utils.ts
---
- https://app.asana.com/0/0/1207870746127154
=> use market's price decimals in Limit/TP/SL entries, expand inputs

src/components/Synthetics/SelectorBase/SelectorBase.tsx
---
- https://app.asana.com/0/0/1207894556767741
=> fixed SelectorBase disabledMessage tooltip display in table

src/components/Synthetics/SubaccountModal/SubaccountModal.scss
Before:
After:
---
- https://app.asana.com/0/0/1207892119638938
=> Fix One-Click Trading modal

src/context/SyntheticsStateContext/SyntheticsStateContextProvider.tsx, src/domain/synthetics/trade/useTradeboxState.ts
---
- https://app.asana.com/0/0/1207929655407326
=> fix switching chainId on accounts page

src/context/SyntheticsStateContext/selectors/tradeSelectors.ts
---
- https://app.asana.com/0/0/1207870746127188
=> Fix SL next values being undefined

src/components/AprInfo/AprInfo.tsx, src/components/TokenCard/TokenCard.tsx, src/domain/synthetics/markets/getIsBaseApyReadyToBeShown.tsx, src/domain/synthetics/markets/useUserEarnings.ts
---
- https://app.asana.com/0/0/1207933473681752
=> Hide apy for new markets

src/components/Synthetics/SelectorBase/SelectorBase.tsx, src/components/TokenSelector/TokenSelector.scss
---
- https://app.asana.com/0/0/1207972476467582
=> Removed SelectorBase chevron's left margin

src/components/Synthetics/TradeBox/TradeBox.tsx, src/components/Synthetics/TradeBox/hooks/useTradeButtonState.tsx
+ refactored button state hook
---
- https://app.asana.com/0/0/1207972476467568
=> Fix: enable main Tradebox button when wallet not connected

src/domain/synthetics/trade/useTradeboxState.ts
---
- https://app.asana.com/0/0/1207972476109456
=> Prevent store trade options with wrong chainId + reset invalid stored data in case of tokens mismatch

src/components/Synthetics/TradeFeesRow/TradeFeesRow.tsx, src/domain/synthetics/common/useIncentiveStats.ts, src/domain/synthetics/tokens/useOracleKeeperFetcher.ts, src/domain/tradingview/__tests__/subscribeBars.spec.ts
---
- https://app.asana.com/0/0/1207829700777489
=> Dynamic rebates

src/components/Synthetics/GmList/GmList.tsx, src/components/Synthetics/GmList/sortGmTokensByField.tsx
---
- https://app.asana.com/0/0/1207940040392511
=> Fix GM APY sorting

src/config/factors.ts
---
- https://app.asana.com/0/0/1208034991818455
=> Decrease cut off limit for traders interview 

src/lib/multicall/executeMulticall.ts
---
- https://app.asana.com/0/0/1208083051719295
=> fix promise with resolvers

src/context/SyntheticsStateContext/SyntheticsStateContextProvider.tsx, src/context/SyntheticsStateContext/hooks/metricsHooks.ts, src/domain/synthetics/positions/usePositionsInfo.ts
---
- https://app.asana.com/0/0/1208083051720352
=> Fix position metrics

src/components/Synthetics/GmList/GmList.tsx, src/components/Synthetics/GmSwap/GmSwapBox/GmDepositWithdrawalBox/GmDepositWithdrawalBox.tsx, src/components/Synthetics/GmSwap/GmSwapBox/GmShiftBox/GmShiftBox.tsx, src/components/Synthetics/GmSwap/GmSwapBox/Swap.tsx, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po
---
- https://app.asana.com/0/0/1208047854088347
=> Update shifts ui

src/domain/tradingview/__tests__/subscribeBars.spec.ts, src/domain/tradingview/useTVDatafeed.ts
---
- https://app.asana.com/0/0/1208082608291213
=> Fix TV chart update on quick period change

src/components/Synthetics/MarketStats/MarketStats.tsx, src/components/Synthetics/MarketTokenSelector/MarketTokenSelector.tsx
---
- https://app.asana.com/0/0/1208100132079373
=> Fix apy order gm dropdown

src/components/Synthetics/GmList/GmList.tsx, src/components/Synthetics/MarketStats/MarketStats.tsx, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po
---
- https://app.asana.com/0/0/1208061895983599
=> Update gm price and apy tooltips

src/context/SyntheticsStateContext/SyntheticsStateContextProvider.tsx, src/domain/synthetics/markets/useMarketsInfoRequest/index.ts, src/lib/metrics/Metrics.ts, src/lib/metrics/storage.ts, src/lib/metrics/useMeasureLoadTime.ts
---
- https://app.asana.com/0/0/1208114239935630
=> Fix metrics in case of page change

src/components/Synthetics/OrderItem/OrderItem.tsx, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po
---
- https://app.asana.com/0/0/1206399503398491
=> "Collateral" to "Collateral delta" text for TP/SL orders

src/components/Synthetics/PositionItem/PositionItem.tsx, src/components/Synthetics/PositionList/PositionList.tsx
---
- https://app.asana.com/0/0/1208061895983584
=> Swap Size and Net Value columns

src/components/Exchange/PositionSeller.css, src/components/TokenSelector/TokenSelector.scss, src/pages/Exchange/Exchange.css
---
- https://app.asana.com/0/0/1207892119638944
=> Double scrolling line on close modal

src/components/Exchange/PositionsList.jsx, src/components/Synthetics/PositionItem/PositionItem.tsx, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po
---
- https://app.asana.com/0/0/1207376960231463
=> Edit collateral and liquidation tooltips

src/components/UserFeedbackModal/UserFeedbackModal.tsx, src/domain/synthetics/userFeedback/types.ts, src/domain/synthetics/userFeedback/useNpsSurvey.tsx, src/domain/synthetics/userFeedback/utils.ts
---
- https://app.asana.com/0/0/1208150547337820
=> Change feedback answers format

src/components/Synthetics/GmAssetDropdown/GmAssetDropdown.tsx, src/components/Synthetics/GmSwap/GmSwapBox/useUpdateByQueryParams.tsx, src/components/Synthetics/MarketStats/MarketStatsWithComposition.tsx, src/components/Synthetics/StatusNotification/GmStatusNotification.tsx, src/components/TokenIcon/TokenIcon.tsx, src/domain/synthetics/orders/simulateExecuteTxn.tsx, tailwind.config.js
- empty pool from /earn table redirect
- borders issues
- GmAssetDropdown z-index
- avalanche failing when read GlvRouter
- Notification title when buyng GMs
=> Fixes issues found in regression

src/lib/multicall/executeMulticall.ts
---
- https://app.asana.com/0/0/1208210628602359
=> disable worker ios

src/lib/multicall/executeMulticall.ts, src/lib/multicall/executeMulticallWorker.ts, src/lib/multicall/multicall.worker.ts
---
- https://app.asana.com/0/0/1208210628602379
=> fix worker throw error

src/domain/synthetics/markets/useGmMarketsApy.ts, src/domain/synthetics/trade/utils/deposit.ts
---
- https://app.asana.com/0/0/1208210628602497
=> fixed page crashes associated with GLV apy and GLV amount input in deposit

src/config/ab.ts, src/domain/synthetics/markets/useMarkets.ts, src/domain/synthetics/markets/useMarketsInfoRequest/index.ts, src/lib/multicall/Multicall.ts
---
- https://app.asana.com/0/0/1208246574123754
=> Rollout testRpcWindowFallback and static markets

src/App/App.tsx, src/components/Exchange/PositionSeller.jsx, src/components/Synthetics/GmList/GmList.tsx, src/components/Synthetics/MarketStats/components/CompositionTable.tsx, src/domain/synthetics/markets/useMarketsInfoRequest/index.ts
---
- https://app.asana.com/0/0/1208178710667859
=> Fix reading properties of undefined

src/config/events.tsx, src/config/markets.ts
---
- https://app.asana.com/0/0/1208252194408180
=> Added BTC GLV config + notification

src/components/Synthetics/GmAssetDropdown/GmAssetDropdown.tsx, src/lib/headlessUiIsMobile.ts, src/pages/Dashboard/AssetDropdown.tsx
---
- https://app.asana.com/0/0/1208214575782278
- https://app.asana.com/0/0/1208222008722531
=> Fix headless ui prevention of closing consecutive dropdowns

src/components/LeverageSlider/LeverageSlider.tsx, src/components/NumberInput/NumberInput.tsx, src/components/SuggestionInput/SuggestionInput.tsx, src/components/Synthetics/TradeBox/TradeBox.tsx, src/components/ToggleSwitch/ToggleSwitch.tsx, src/domain/synthetics/trade/useTradeboxState.ts
---
- https://app.asana.com/0/0/1206513187657165
=> Leverage num input

src/components/Synthetics/GmSwap/GmSwapBox/GmDepositWithdrawalBox/GmDepositWithdrawalBox.tsx, src/components/Synthetics/GmSwap/GmSwapBox/useUpdateByQueryParams.tsx
---
- https://app.asana.com/0/0/1208258355009385
=> Fixed GLV's pool dropping when switching from one GLV to another

src/components/Button/Button.tsx, src/components/Synthetics/TradeBox/TradeBoxRows/OneClickTrading.tsx
---
- https://app.asana.com/0/0/1208028460890343
=> Disable 1CT modal trigger on enter press in tradebox

src/components/Synthetics/GmSwap/GmSwapBox/GmDepositWithdrawalBox/InfoRows.tsx, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po
---
- https://app.asana.com/0/0/1208269257416079
=> Refactor InfoRows component and add alert for endangered pools

src/components/Synthetics/PositionItem/PositionItem.tsx
---
- https://app.asana.com/0/0/1207859668197452
- https://app.asana.com/0/0/1208301955788725
- https://app.asana.com/0/0/1208301955788744
=> Accrued borrow fee missing negative sign

src/components/Synthetics/NetworkFeeRow/NetworkFeeRow.tsx
---
- https://app.asana.com/0/0/1206862808656395
=> Add one more decimal to network fee token values

src/components/Synthetics/PositionSeller/PositionSeller.tsx, src/components/Synthetics/TradeBox/TradeBox.tsx, src/components/Synthetics/TradeBox/hooks/useTradeboxAvailablePriceImpactValues.ts, src/components/Synthetics/TradeBox/hooks/useTradeboxTransactions.tsx, src/context/SyntheticsStateContext/selectors/tradeboxSelectors/index.ts, src/domain/synthetics/trade/useTradeboxState.ts, src/domain/synthetics/trade/utils/validation.ts
---
- https://app.asana.com/0/0/1208301955788681
=> Fix tp/sl wrong type on quick enter

src/components/Exchange/SwapBox.jsx
---
- https://app.asana.com/0/0/1208260565895653
=> Fix parsing of leverage option in SwapBox component

src/lib/contracts/utils.ts, src/lib/metrics/Metrics.ts, src/lib/metrics/emitMetricEvent.ts, src/lib/oracleKeeperFetcher.ts
---
- https://app.asana.com/0/0/1208359174755866
=> Fix value.hash error

src/config/ab.ts, src/domain/synthetics/markets/useMarketsInfoRequest/buildMarketsConfigsRequest.ts, src/domain/synthetics/markets/useMarketsInfoRequest/buildMarketsValuesRequest.ts, src/domain/synthetics/markets/useMarketsInfoRequest/index.ts, src/lib/multicall/Multicall.ts, src/lib/multicall/executeMulticall.ts, src/lib/multicall/types.ts
---
- https://app.asana.com/0/0/1208378807085397
=> roll out prebuild market keys ab

src/lib/rpc/getProviderNameFromUrl.ts
---
- https://app.asana.com/0/0/1208378807085414
=> fix metrics hostname

src/components/MarketWithDirectionLabel/MarketWithDirectionLabel.tsx, src/components/Synthetics/ClaimModal/ClaimModal.tsx, src/components/Synthetics/ClaimablePositionPriceImpactRebateModal/ClaimablePositionPriceImpactRebateModal.tsx
---
- https://app.asana.com/0/0/1207693543129644
=> claims row formatting

src/components/Exchange/PositionSeller.jsx, src/lib/contracts/contractFetcher.ts, src/lib/wallets/useEthersSigner.ts
---
- https://app.asana.com/0/0/1208359635773823
=> Errors undefined 2

src/config/ab.ts, src/lib/multicall/Multicall.ts, src/lib/rpc/bestRpcTracker.ts
---
- https://app.asana.com/0/0/1208412295723154
=> add block metrics + rollback alchemy exp

src/components/Synthetics/TableMarketFilter/MarketFilterBase.tsx, src/components/Synthetics/TableMarketFilter/MarketFilterLongShort.tsx, src/context/SyntheticsStateContext/SyntheticsStateContextProvider.tsx, src/domain/synthetics/markets/useMarketTokensData.ts
---
- https://app.asana.com/0/0/1208377009474108
=> Table filters dont wait GLV

src/components/AprInfo/AprInfo.tsx, src/components/Synthetics/GmList/GmList.tsx, src/components/Synthetics/MarketStats/MarketStatsWithComposition.tsx, src/components/Synthetics/MarketTokenSelector/MarketTokenSelector.tsx, src/components/TokenCard/TokenCard.tsx, src/config/ethena.ts, src/config/tbtc.ts, src/domain/synthetics/common/incentivesAirdropMessages.ts, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po, src/pages/Stake/StakeV2.tsx
---
- https://app.asana.com/0/0/1208359641593904
=> TBTC incentives

src/components/TokenCard/TokenCard.tsx, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po, src/pages/Home/Home.tsx
---
- https://app.asana.com/0/0/1208258355632304
=> Refactor BuyLink component in TokenCard

src/config/bridging.tsx, src/config/events.tsx, src/config/static/markets.ts, src/config/tokens.ts, src/domain/synthetics/common/incentivesAirdropMessages.ts
---
- https://app.asana.com/0/0/1208359641593898
=> in TBTC make t lowercase to be tBTC

src/config/ab.ts, src/lib/rpc/bestRpcTracker.ts
---
- https://app.asana.com/0/0/1208433787033193
=> rollout smart rpc swithcing

src/components/Synthetics/GmList/GmList.tsx, src/components/Synthetics/GmList/sortGmTokensByField.tsx, src/pages/MarketPoolsPage/MarketPoolsPage.tsx
---
- https://app.asana.com/0/0/1208498368384386
=> Fixed APY sorting

src/components/Synthetics/ChartTokenSelector/ChartTokenSelector.tsx
---
- https://app.asana.com/0/0/1208456477171373
=> Swap favorites

src/config/subgraph.ts
---
- https://app.asana.com/0/0/1208399041303803
=> fix fuji subgraph

src/domain/stats/useFeesSummary.ts, src/pages/Dashboard/DashboardV2.tsx, src/pages/Dashboard/OverviewCard.tsx, src/pages/Dashboard/StatsCard.tsx
---
- https://app.asana.com/0/0/1208493594490516
=> Fix dashboard stats

src/App/AppRoutes.tsx, src/components/Synthetics/TVChart/TVChart.tsx, src/context/SyntheticsStateContext/useCollectSyntheticsMetrics.ts, src/context/WebsocketContext/WebsocketContextProvider.tsx, src/domain/synthetics/positions/usePositions.ts, src/domain/tradingview/useTVDatafeed.ts, src/lib/contracts/utils.ts, src/lib/isPageRefreshed.ts, src/lib/metrics/Metrics.ts, src/lib/metrics/emitMetricEvent.ts, src/lib/metrics/index.ts, src/lib/metrics/types.ts, src/lib/metrics/useAccountInitedMetric.ts, src/lib/metrics/useOpenAppMetric.ts, src/lib/multicall/Multicall.ts, src/lib/multicall/executeMulticall.ts, src/lib/multicall/executeMulticallWorker.ts, src/lib/rpc/bestRpcTracker.ts
---
- https://app.asana.com/0/0/1208508754927009
=> Additional metrics 2

src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po, src/pages/Ecosystem/Ecosystem.jsx
---
- https://app.asana.com/0/0/1208508754927091
=> mention tradingview in ecosystem

src/pages/Actions/ActionsRouter.tsx, src/pages/Actions/ActionsV1/ActionsV1.tsx
---
- https://app.asana.com/0/0/1208508345779451
=> Fix account dashboard v1 pagination

src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po, src/pages/Home/Home.tsx
---
- https://app.asana.com/0/0/1208484953337270
=> Modify homepage three tokens text

src/components/AddressDropdown/AddressDropdown.tsx, src/components/Avatar/Avatar.tsx, src/lib/legacy.ts, src/lib/wallets/rainbowKitConfig.ts, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po
---
- https://app.asana.com/0/0/1208536704978563
=> Fix Davatar blockings

src/domain/synthetics/positions/usePositionsInfo.ts
---
- https://app.asana.com/0/0/1208550769259321
=> fix weth icon

src/components/Tooltip/Tooltip.scss
---
- https://app.asana.com/0/0/1208550769259330
=> Fix tooltip width

src/components/TVChartContainer/TVChartContainer.tsx, src/domain/tradingview/useTVDatafeed.ts
get price decimals directly from current candle price instead of chartToken
---
- https://app.asana.com/0/0/1208566025770942
=> Hotfix chart price decimals

src/context/SyntheticsStateContext/selectors/orderEditorSelectors.ts
---
- https://app.asana.com/0/0/1208584696790514
=> hotfix: trigger price check

src/components/Synthetics/ChartTokenSelector/ChartTokenSelector.tsx, src/components/Synthetics/SelectorBase/SelectorBase.tsx
---
- https://app.asana.com/0/0/1208566025770926
- https://app.asana.com/0/0/1208566025770914
=> Fix missing coins chart token selector position

src/domain/synthetics/markets/useGmMarketsApy.ts
---
- https://app.asana.com/0/0/1208550766477865
=> Fixed max GM APY calculation in case when there's no incentives

src/config/ab.ts, src/config/contracts.ts, src/context/SyntheticsEvents/SyntheticsEventsProvider.tsx, src/context/WebsocketContext/subscribeToEvents.ts, src/domain/synthetics/tokens/useTokenAllowanceData.ts, src/pages/Stake/StakeV1.jsx
---
- https://app.asana.com/0/0/1208595345585144
=> WS approval events without experiment

src/config/events.tsx
---
- https://app.asana.com/0/0/1208634093673499
=> buyback announce

src/config/ab.ts, src/domain/synthetics/markets/useMarketsInfoRequest/useFastMarketsInfoRequest.ts
---
- https://app.asana.com/0/0/1208681609985166
=> Roll out fast market info

src/App/App.tsx, src/domain/synthetics/trade/useTradeParamsProcessor.ts, src/lib/contracts/callContract.tsx, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po, src/pages/Stake/StakeV2.tsx
---
- https://app.asana.com/0/0/1208540731771152
=> Gmx rewards part 2

src/config/ab.ts, src/context/SyntheticsEvents/SyntheticsEventsProvider.tsx, src/context/TokensBalancesContext/TokensBalancesContextProvider.tsx, src/domain/synthetics/markets/useGlvMarkets.ts, src/domain/synthetics/markets/useMarketTokensData.ts, src/domain/synthetics/tokens/useTokenBalances.ts
---
- https://app.asana.com/0/0/1208735399438573
=> Rollout ws balances ab

src/config/constants.ts
---
- https://app.asana.com/0/0/1208708784187863
=> increase interview cutoff

src/components/Synthetics/TradeBox/MarketPoolSelectorRow.tsx, src/components/Synthetics/TradeBox/TradeBox.tsx, src/components/Synthetics/TradeBox/TradeBoxRows/CollateralSelectorRow.tsx, src/components/Synthetics/TradeBox/hooks/useBestMarketAddress.ts, src/components/Synthetics/TradeBox/hooks/useTradeboxChanges.ts, src/components/Synthetics/TradeboxPoolWarnings/TradeboxPoolWarnings.tsx, src/domain/synthetics/trade/useTradeboxState.ts, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po
---
- https://app.asana.com/0/0/1208681609985165
=> new pool selection logic

src/components/Exchange/SwapBox.jsx, src/pages/Exchange/Exchange.tsx
---
- https://app.asana.com/0/0/1208734047522491
=> Hotfix: fix v1 unknown token

src/config/ab.ts, src/domain/synthetics/orders/prepareOrderTxn.ts
---
- https://app.asana.com/0/0/1208782494490816
=> Roll out parallel simulations

src/components/AprInfo/AprInfo.tsx, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po
---
- https://app.asana.com/0/0/1208633893056973
=> hide zero apy if not ready

src/components/Exchange/PositionShareCard.tsx
---
- https://app.asana.com/0/0/1208804219569601
=> fix v1 share

src/components/Exchange/PositionShareCard.tsx
---
- https://app.asana.com/0/0/1208705738983356
=> fix share visual multiplier

src/components/Synthetics/TradeBox/TradeBox.tsx, src/components/Synthetics/TradeboxPoolWarnings/TradeboxPoolWarnings.tsx, src/components/TokenCard/TokenCard.tsx, src/context/SyntheticsStateContext/selectors/tradeboxSelectors/selectTradeboxChooseSuitableMarket.ts, src/lib/metrics/types.ts, src/lib/metrics/utils.ts, src/lib/userAnalytics/types.ts, src/lib/userAnalytics/useConfigureUserAnalyticsProfile.ts, src/lib/userAnalytics/utils.ts
1. Remove MarketSelectedEvent
2. Unify pair field to contain a full market names
3. add sizeDeltaUsd to tradeBox events (amountUsd for swaps)
4. stop sending isLeverageEnabled for decrease orders
=> Hotfix: update user analytics events

src/components/Synthetics/PositionSeller/PositionSeller.tsx, src/components/Synthetics/TradeBox/TradeBox.tsx, src/domain/synthetics/orders/useSetOrdersAutoCancelByQueryParams.ts, src/domain/synthetics/trade/useMaxAutoCancelOrdersState.tsx
---
- https://app.asana.com/0/0/1208637000551077
=> fix max auto cancel orders amount

src/components/Synthetics/TradeBox/TradeBoxRows/LimitAndTPSLRows.tsx, src/domain/synthetics/sidecarOrders/useSidecarOrdersGroup.ts, src/domain/synthetics/sidecarOrders/utils.ts
---
- https://app.asana.com/0/0/1208693952674458
=> Fix sideorder pnl tooltip decimals

src/components/Synthetics/TradeBox/hooks/useTradeboxTransactions.tsx, src/lib/metrics/types.ts, src/lib/metrics/utils.ts
---
- https://app.asana.com/0/0/1208880413597525
=> Hotfix: add allowance metric

src/components/Synthetics/TradeFeesRow/TradeFeesRow.tsx, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po
---
- https://app.asana.com/0/0/1208046683327909
=> fix fee rebate case

src/components/Synthetics/PositionItem/PositionItem.tsx, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po
---
- https://app.asana.com/0/0/1208633893056998
=> pnl mobile label

src/components/Synthetics/Claims/ClaimableCard.tsx, src/components/Synthetics/Claims/ClaimableCardUI.tsx, src/components/Synthetics/Claims/SettleAccruedCard.tsx, src/components/Synthetics/PositionItem/PositionItem.tsx, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po
---
- https://app.asana.com/0/0/1206736505163394
=> update claim tab messages

src/lib/numbers.spec.ts, src/lib/numbers.ts
---
- https://app.asana.com/0/0/1208934474602868
=> fix negative price crash

src/domain/tradingview/DataFeed.ts
---
- https://app.asana.com/0/0/1208930716810008
=> Fix chart slow candle load

sdk/src/types/amounts.ts, sdk/src/types/trade.ts, src/config/markets.ts, src/domain/synthetics/__tests__/routing/swapPath.spec.ts, src/domain/synthetics/trade/types.ts, src/domain/synthetics/trade/utils/swapRouting.ts
---
- https://app.asana.com/0/0/1208952874405929
=> Limit swap routes

src/config/chains.ts
---
- https://app.asana.com/0/0/1208966062671890
=> Hotfix: Disable drpc

src/components/MarketSelector/GmPoolsSelectorForGlvMarket.tsx, src/components/MarketSelector/PoolSelector.tsx, src/components/Synthetics/GmList/GmList.tsx, src/components/Synthetics/MarketTokenSelector/MarketTokenSelector.tsx
---
- https://app.asana.com/0/0/1208974058754588
=> Fix swap only market category filtering

package.json, sdk/scripts/prebuild/index.ts, sdk/scripts/prebuild/prebuildKinkModelMarketRatesKeys.ts, sdk/src/configs/dataStore.ts, sdk/src/modules/markets/types.ts, sdk/src/prebuilt/hashedKinkModelMarketRatesKeys.json, sdk/src/prebuilt/index.ts, src/config/dataStore.ts, src/config/factors.ts, src/domain/synthetics/markets/useKinkModelMarketsRates.ts, src/pages/SyntheticsStats/SyntheticsStats.tsx, src/prebuilt/hashedKinkModelMarketRatesKeys.json
---
- https://app.asana.com/0/0/1208865803017770
=> Update stats borrowing rates

src/components/Synthetics/CollateralSelector/CollateralSelector.scss, src/components/Synthetics/CollateralSelector/CollateralSelector.tsx, src/components/Synthetics/PoolSelector2/PoolSelector2.scss, src/components/Synthetics/PoolSelector2/PoolSelector2.tsx, src/components/Synthetics/SelectorBase/SelectorBase.scss, src/components/Synthetics/SelectorBase/SelectorBase.tsx, src/components/Synthetics/TradeBox/TradeBoxRows/CollateralSelectorRow.tsx, src/components/Table/Table.tsx, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po
---
- https://app.asana.com/0/0/1208930716809989
=> Simplify dropdowns

src/domain/synthetics/markets/useGlvMarkets.ts
---
- https://app.asana.com/0/0/1209029001765122
=> Fixed GLV min/max prices parsing

src/components/AprInfo/AprInfo.tsx, src/components/SearchInput/SearchInput.tsx, src/components/Synthetics/Claims/filters/ActionFilter.tsx, src/components/Synthetics/CollateralSelector/CollateralSelector.tsx, src/components/Synthetics/GmSwap/GmSwapBox/GmDepositWithdrawalBox/GmDepositWithdrawalBox.tsx, src/components/Synthetics/GmSwap/GmSwapBox/GmShiftBox/GmShiftBox.tsx, src/components/Synthetics/OrderItem/OrderItem.tsx, src/components/Synthetics/TradeBox/TradeBox.tsx, src/components/Synthetics/TradeHistory/TradeHistoryRow/utils.spec.ts, src/components/Synthetics/TradeHistory/TradeHistoryRow/utils/position.ts, src/components/Synthetics/TradeHistory/filters/ActionFilter.tsx, src/components/TokenSelector/TokenSelector.tsx, src/config/ethena.ts, src/domain/synthetics/claimHistory/useClaimHistory.ts, src/domain/synthetics/tradeHistory/useTradeHistory.ts, src/lib/numbers.spec.ts, src/lib/numbers.ts, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po
---
- https://app.asana.com/0/0/1209010085433589
- https://app.asana.com/0/0/1209010085433599
- https://app.asana.com/0/0/1208997186325361
- https://app.asana.com/0/0/1209010085433654
- https://app.asana.com/0/0/1209010085433643
- https://app.asana.com/0/0/1209010085433666
- https://app.asana.com/0/0/1209010085433578
=> UI improvements

src/components/Synthetics/ExecutionPriceRow.tsx, src/components/Synthetics/TradeFeesRow/TradeFeesRow.tsx
---
- https://app.asana.com/0/0/1208930716810044
=> Remove percent of collateral

src/components/Synthetics/TradeFeesRow/TradeFeesRow.tsx
---
- https://app.asana.com/0/0/1209043569003335
=> Change Swap Fees ordering when closing a position

src/config/events.tsx
---
- https://app.asana.com/0/0/1209065539054368
=> Reduction of open/close fees announcement

src/components/Synthetics/ChartTokenSelector/ChartTokenSelector.tsx
---
- https://app.asana.com/0/0/1209045376366330
=> fixed pool text color in success toast

.github/workflows/update-testing.yml
---
- https://app.asana.com/0/0/1209045380823625
=> [DO NOT MERGE] Test branch

src/components/Glp/GlpSwap.jsx, src/components/Referrals/AffiliatesStats.tsx, src/components/Referrals/TradersStats.tsx, src/components/Synthetics/Claims/ClaimHistoryRow/ClaimCollateralHistoryRow.tsx, src/components/Synthetics/Claims/ClaimHistoryRow/ClaimFundingFeesHistoryRow.tsx, src/components/Synthetics/GmList/GmTokensTotalBalanceInfo.tsx, src/components/Synthetics/MarketStats/MarketStatsWithComposition.tsx, src/components/Synthetics/OrderEditor/OrderEditor.tsx, src/components/Synthetics/OrderItem/OrderItem.tsx, src/components/Synthetics/PositionItem/PositionItem.tsx, src/components/Synthetics/TradeBox/TradeBoxRows/MinReceiveRow.tsx, src/components/Synthetics/TradeHistory/TradeHistoryRow/utils.spec.ts, src/components/Synthetics/TradeHistory/TradeHistoryRow/utils/swap.ts, src/components/Synthetics/UserIncentiveDistributionList/UserIncentiveDistributionList.tsx, src/components/Tooltip/Tooltip.tsx, src/lib/numbers.spec.ts, src/lib/numbers.ts, src/pages/Earn/EscrowedGmxCard.tsx, src/pages/Earn/GlpCard.tsx, src/pages/Earn/GmxAndVotingPowerCard.tsx, src/pages/Earn/TotalRewardsCard.tsx, src/pages/Earn/Vesting.tsx, src/pages/LeaderboardPage/components/LeaderboardPositionsTable.tsx
---
- https://app.asana.com/0/0/1209045376366345
=> Collateral formattiing

src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po, src/pages/Earn/EarnV2.tsx, src/pages/MarketPoolsPage/MarketPoolsPage.tsx
---
- https://app.asana.com/0/0/1209098942533174
=> /earn fix texts

src/domain/tradingview/DataFeed.ts
---
- https://app.asana.com/0/0/1209139231063539
=> Hotfix: Disable repeating candles events

src/components/Referrals/JoinReferralCode.jsx, src/components/Referrals/JoinReferralCode.tsx, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po
---
- https://app.asana.com/0/0/1209240599149450
- https://app.asana.com/0/0/1209246670377649
=> Hotfix: referral page crash

sdk/src/configs/chains.ts, src/components/Exchange/SwapBox.jsx, src/config/chains.ts, src/lib/chains/index.ts
---
- https://app.asana.com/0/0/1209242154397099
=> fixed network switching to fuji

src/domain/synthetics/positions/usePositionsTotalCollateral.ts, src/pages/Dashboard/OverviewCard.tsx
This reverts commit c4ff16502351d4c84acb6e2b0cb9e87f3539f3ed.
---
- https://app.asana.com/0/0/1209014954506241
=> Revert "Revert "Merge pull request #1482 from gmx-io/total-positions-collateral-resolver""

src/domain/stats/useV1FeesInfo.ts, src/domain/synthetics/stats/useV2FeesInfo.ts, src/domain/synthetics/stats/useV2Stats.ts, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po, src/pages/Dashboard/OverviewCard.tsx
Hotfix: fixed fees tooltip in dashboard to consider fees entries from start of epoch and annualized based on 7 days
---
- https://app.asana.com/0/0/1209298573246090
=> Hotfix: fixed fees tooltip in dashboard

src/pages/ParseTransaction/ParseTransaction.tsx, src/pages/ParseTransaction/formatting.tsx
---
- https://app.asana.com/0/0/1209298573246050
=> improvements in parse transaction page

src/components/Synthetics/ExpandableRow.tsx, src/components/Synthetics/TradeBox/TradeBox.tsx
---
- https://app.asana.com/0/0/1209398486451613
=> Hotfix facelift fix 1

src/components/Synthetics/PositionSeller/PositionSeller.tsx
---
- https://app.asana.com/0/0/1209430316281293
=> Fix position seller race condition

src/components/InterviewModal/InterviewModal.tsx, src/components/InterviewToast/InterviewToast.tsx, src/config/constants.ts, src/config/localStorage.ts, src/domain/synthetics/markets/utils.ts, src/domain/synthetics/userFeedback/useInterviewNotification.tsx, src/domain/synthetics/userFeedback/useLpInterviewNotification.tsx, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po, src/pages/MarketPoolsPage/MarketPoolsPage.tsx, src/pages/SyntheticsPage/SyntheticsPage.tsx
---
- https://app.asana.com/0/0/1209077230989327
=> Add LP interview notification feature

src/domain/synthetics/__tests__/fees/executionFee.spec.ts, src/domain/synthetics/fees/utils/executionFee.ts
---
- https://app.asana.com/0/0/1209508302127101
=> Hotfix remove extra premium

src/config/events.tsx
---
- https://app.asana.com/0/0/1209532529255173
=> Hotfix Add Stop Market Orders event to events

src/domain/synthetics/trade/utils/swapRouting.ts
---
- https://app.asana.com/0/0/1209532529255197
- https://app.asana.com/0/0/1209530518717597
=> Hotfix: swap routing

.github/workflows/pr-tests.yml, src/domain/synthetics/__tests__/routing/swapPath.spec.ts
---
- https://app.asana.com/0/0/1209584378211173
=> Hotfix: Fix swap tests and ci checks

src/components/Exchange/ExchangeTVChart.jsx, src/components/NetworkDropdown/NetworkDropdown.css, src/components/NetworkDropdown/NetworkDropdown.tsx, src/components/Synthetics/AllowedSwapSlippageInputRowImpl/AllowedSwapSlippageInputRowImpl.tsx, src/components/Synthetics/ChartTokenSelector/ChartTokenSelector.tsx, src/components/Synthetics/PositionItem/PositionItem.scss, src/components/Synthetics/PositionItem/PositionItem.tsx, src/components/Synthetics/TVChart/ChartHeader.tsx, src/components/Synthetics/TVChart/TVChart.scss, src/components/VersionSwitch/VersionSwitch.scss, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po, src/pages/Dashboard/DashboardPageTitle.tsx, src/pages/Exchange/Exchange.css, src/pages/UiPage/UiPage.tsx, tailwind.config.js
**Task**: [Trade page minor UI updates](https://app.asana.com/0/1204313444805313/1209550756168506)
1. Positions table update  
<details>
<summary>Screenshots</summary>
</details>
2. Positions card update  
<details>
<summary>Screenshots</summary>
</details>
3. Markets popup mobile update  
<details>
<summary>Screenshots</summary>
</details>
4. Markets popup desktop update  
<details>
<summary>Screenshots</summary>
</details>
5. Version switch position and UI update  
<details>
<summary>Screenshots</summary>
</details>
=> Trade page minor UI updates

src/components/Synthetics/NetworkFeeRow/NetworkFeeRow.tsx
**Task:** https://app.asana.com/0/1204313444805313/1209080350236938
**Screenshot**:
=> Take into account the estimated fee refund for the default network fee display

src/pages/AccountDashboard/DailyAndCumulativePnL.tsx
**Task:** https://app.asana.com/0/1204313444805313/1209255967904491
**Screenshot:**
=> Show minimum seven points in PnL analysis

src/components/TVChartContainer/TVChartContainer.tsx
---
- https://app.asana.com/0/0/1209606197089358
=> Refactor TradingView chart symbol change condition

src/components/Synthetics/TradeBox/hooks/useTradeboxTransactions.tsx, src/config/ab.ts, src/domain/synthetics/externalSwaps/openOcean.ts, src/domain/synthetics/externalSwaps/useExternalSwapOutputRequest.ts, src/domain/synthetics/orders/createIncreaseOrderTxn.ts, src/lib/metrics/types.ts, src/lib/metrics/utils.ts
---
- https://app.asana.com/0/0/1209671724457541
=> Hotfix: Additional external swap metrics

src/components/NpsModal/NpsModal.tsx, src/components/Textarea/Textarea.scss, src/components/Textarea/Textarea.tsx, src/components/UserFeedbackModal/UserFeedbackModal.tsx, src/domain/synthetics/userFeedback/types.ts, src/domain/synthetics/userFeedback/useNpsSurvey.tsx, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po, tailwind.config.js
**Task**: https://app.asana.com/0/1204313444805313/1209672663802146/f
**Screenshots**:
=> Contact field for Feedback and NPS survey forms

src/components/MintableAmount/MintableAmount.tsx, src/components/Synthetics/ChartTokenSelector/ChartTokenSelector.tsx, src/components/Synthetics/GmList/GmListItem.tsx, src/components/Synthetics/GmList/GmTokensTotalBalanceInfo.tsx, src/components/Synthetics/GmList/TokenValuesInfoCell.tsx, src/components/Synthetics/MarketStats/MarketStatsWithComposition.tsx, src/img/ic_settings_16.svg, src/img/ic_settings_24.svg
**Task**: https://app.asana.com/0/1204313444805313/1209657245760326/f
**Screenshots**:
=> Minor fixes discovered in r63 regression

src/pages/ParseTransaction/ParseTransaction.tsx, src/pages/ParseTransaction/formatting.tsx, src/pages/ParseTransaction/parseTxEvents.ts
---
- https://app.asana.com/0/0/1209606197089350
=>  added links to explorer in parse tx page, added roleKey descriptions

src/components/DepthChart/DepthChart.tsx, src/components/OrderEditorContainer/OrderEditorContainer.tsx, src/components/Synthetics/OrderEditor/OrderEditor.tsx, src/components/Synthetics/OrderItem/OrderItem.tsx, src/components/Synthetics/PositionItem/PositionItem.tsx, src/components/TVChartContainer/DynamicLines.tsx, src/context/SyntheticsStateContext/hooks/orderEditorHooks.ts, src/context/SyntheticsStateContext/selectors/orderEditorSelectors.ts, src/domain/synthetics/orders/simulateExecuteTxn.tsx, src/domain/synthetics/orders/types.ts, src/domain/synthetics/orders/useOrderEditorState.ts, src/lib/userAnalytics/UserAnalytics.ts, src/lib/userAnalytics/types.ts, src/lib/userAnalytics/useConfigureUserAnalyticsProfile.ts, src/lib/userAnalytics/utils.ts
**Task**: https://app.asana.com/0/1204313444805313/1209739146442901/f
=> Depth chart and orders from chart adoption

src/pages/LeaderboardPage/components/LeaderboardContainer.tsx
---
- https://app.asana.com/0/0/1209785411873180
=> Remove inline type on leaderboard competition tabs

src/pages/Ecosystem/ecosystemConstants.tsx
---
- https://app.asana.com/0/0/1209808650848621
=> Update DeBank link to include HTTPS

src/components/TokenCard/TokenCard.tsx, src/domain/synthetics/markets/useGlvMarkets.ts, src/pages/ParseTransaction/ParseTransaction.tsx
---
- https://app.asana.com/0/0/1209524425917387
=> Filter unsupported markets from GLV

sdk/src/utils/swap/__tests__/buildMarketsAdjacencyGraph.spec.ts, sdk/src/utils/swap/__tests__/findReachableTokens.spec.ts, sdk/src/utils/swap/buildMarketsAdjacencyGraph.ts, sdk/src/utils/swap/findReachableTokens.ts, sdk/src/utils/swap/findSwapPathsBetweenTokens.ts, src/context/SyntheticsStateContext/selectors/positionSellerSelectors.ts
---
- https://app.asana.com/0/0/1209827223025320
=> Hotfix position seller TBTC receive selection

src/components/SettingsModal/SettingsModal.tsx, src/config/ab.ts, src/domain/synthetics/externalSwaps/useExternalSwapHandler.tsx
---
- https://app.asana.com/0/0/1209855464802931
=> Hotfix: Rollout External Swaps AB

src/config/ab.ts, src/context/SyntheticsStateContext/selectors/tradeSelectors.ts, src/domain/synthetics/externalSwaps/useExternalSwapHandler.tsx
---
- https://app.asana.com/0/0/1209904418705542
=> Hotfix creating tpsl from short stop market tradebox

sdk/src/utils/trade/amounts.ts
---
- https://app.asana.com/0/0/1209920844970166
=> Fix getting estimated leverage 

src/components/Footer/Footer.tsx, src/components/Synthetics/TVChart/Chart.tsx, src/components/Synthetics/TradeBox/TradeBoxRows/OneClickTrading.tsx, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po, src/pages/Exchange/Exchange.css, src/pages/SyntheticsPage/SyntheticsPage.tsx, src/styles/Shared.scss
---
- https://app.asana.com/0/0/1209800727587278
=> Trade page adaptive layout

src/domain/synthetics/orders/simulateExecuteTxn.tsx
---
- https://app.asana.com/0/0/1209948736663331
=> Hotfix: Increase simulation price timestamp

src/lib/userAnalytics/UserAnalytics.ts, src/lib/userAnalytics/useConfigureUserAnalyticsProfile.ts
---
- https://app.asana.com/0/0/1210001294840204
=> Track user settings in mixpanel

src/components/Synthetics/TradeboxPoolWarnings/TradeboxPoolWarnings.tsx, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po
---
- https://app.asana.com/0/0/1209959194016322
=> Updated save on fees warning content

src/components/Synthetics/PositionSeller/PositionSeller.tsx, src/context/SyntheticsStateContext/selectors/tradeboxSelectors/selectTradeboxTradeErrors.ts, src/domain/synthetics/trade/utils/validation.ts, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po
---
- https://app.asana.com/0/0/1209945904060019
=> Handle min position size in decrease/increase errors

sdk/package.json, sdk/src/modules/orders/helpers.ts, sdk/tsconfig.cjs.json, sdk/tsconfig.json
---
- https://app.asana.com/0/0/1210109066925473
=> Fixed SDK exports, added validation for synthetic tokens

src/components/Synthetics/TradeboxPoolWarnings/TradeboxPoolWarnings.tsx, src/lib/userAnalytics/types.ts, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po
---
- https://app.asana.com/0/0/1210055700621613
=> Save on fees warning analytics events

sdk/README.md, sdk/package.json, sdk/src/modules/orders/helpers.spec.ts, sdk/src/modules/orders/helpers.ts, sdk/src/modules/orders/orders.ts
---
- https://app.asana.com/0/0/1210204933992836
=> [sdk]: Added validation for .long/short pay and collateral token, fixed README

src/domain/synthetics/tradeHistory/useTradeHistory.ts
---
- https://app.asana.com/0/0/1210126709281178
- https://app.asana.com/0/0/1210032397372100
=> Fixed trade history market filters

.github/workflows/publish-sdk.yml, sdk/package.json, sdk/src/modules/markets/query-builders.ts
---
- https://app.asana.com/0/0/1210364085826765
=> [sdk]: Fix build markets values request

src/components/Synthetics/GmList/GlvList.tsx, src/components/Synthetics/GmList/GmList.tsx, src/domain/synthetics/governance/useGovTokenDelegates.ts, src/domain/synthetics/tokens/useTokenBalances.ts, src/lib/chains/useRealChainIdWarning.ts, src/lib/wallets/useEthersSigner.ts, src/lib/wallets/useWallet.ts, src/pages/TestPermits/TestPermits.tsx
---
- https://app.asana.com/0/0/1210414084798130
=> Hotfix: Fix Signer doesn't match receiver address

sdk/package.json, sdk/src/modules/orders/helpers.ts
---
- https://app.asana.com/0/0/1210578718838831
=> [sdk]: fixed isLong hardcoded in increaseOrderParams

src/components/Synthetics/GmList/GmListItem.tsx
---
- https://app.asana.com/0/0/1210598915376230
=> Change color on pools snapshots

src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po
https://app.asana.com/1/1538917451150/project/1204313444805313/task/1210601110576867?focus=true
=> Fix conflicts in translations

sdk/src/utils/__tests__/orderTransactions/swapOrders.spec.ts, sdk/src/utils/orderTransactions.ts, src/components/Synthetics/StatusNotification/OrderStatusNotification.tsx, src/context/SyntheticsEvents/types.ts, src/context/SyntheticsEvents/utils.ts, src/context/SyntheticsStateContext/selectors/transactionsSelectors/tradeBoxOrdersSelectors.ts, src/domain/synthetics/orders/useOrderTxnCallbacks.tsx
---
- https://app.asana.com/0/0/1210431778994454
=> Bugfix: show best output of swap instead worst

src/components/Synthetics/TradeBox/Curtain.tsx, src/components/Synthetics/TradeBox/TradeBox.tsx, src/components/Synthetics/TradeBox/hooks/useTradeButtonState.tsx
---
- https://app.asana.com/0/0/1210463119815013
=> Mobile autoclose

sdk/src/utils/__tests__/orderTransactions/swapOrders.spec.ts, sdk/src/utils/orderTransactions.ts, src/context/SyntheticsEvents/types.ts, src/context/SyntheticsEvents/utils.ts, src/domain/synthetics/orders/useOrderTxnCallbacks.tsx
---
- https://app.asana.com/0/0/1210661595752020
=> Make expectedOutputAmount only UI property

sdk/src/configs/contracts.ts
---
- https://app.asana.com/0/0/1210739118612071
=> Hotfix add missing contracts for botanix

src/config/events.tsx, src/config/static/markets.ts
---
- https://app.asana.com/0/0/1211172587996773
=> Hotfix: re-enable pBTC market on Botanix

src/App/MainRoutes.tsx, src/components/BuyCards/BuyCards.tsx, src/components/Footer/Footer.tsx, src/components/Footer/constants.tsx, src/context/GlobalContext/GlobalContextProvider.tsx, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/ru/messages.po, src/locales/zh/messages.po, src/pages/Stake/EscrowedGmxCard.tsx, src/pages/Stake/GmxAndVotingPowerCard.tsx, src/pages/Stake/Stake.tsx, src/pages/Stake/Vesting.tsx
---
- https://app.asana.com/0/0/1211218779191295
=> Remove V1 UI

src/components/Synthetics/TradeBox/TradeBox.tsx
---
- https://app.asana.com/0/0/1211307291076849
=> Fix twap tradebox

src/components/EventToast/useEventToast.tsx, src/config/events.tsx
---
- https://app.asana.com/0/0/1211369959679232
=> Hotfix add MKR delisting event

src/config/localStorage.ts, src/domain/synthetics/accountStats/useIsLargeAccountData.ts
---
- https://app.asana.com/0/0/1211383981693703
=> upd large account params

src/context/SyntheticsStateContext/selectors/chartSelectors/index.ts
---
- https://app.asana.com/0/0/1211405084606865
=> Fix open interest rounding in chart header

sdk/src/configs/chains.ts, src/components/TradeHistory/TradeHistoryRow/TradeHistoryRow.tsx, src/lib/wallets/useAccountType.ts, src/locales/de/messages.po, src/locales/es/messages.po, src/locales/fr/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/pages/ParseTransaction/ParseTransaction.tsx
---
- https://app.asana.com/0/0/1211466763604615
=> support fetching Safe singleton addresses from API

src/components/UserIncentiveDistributionList/ClaimableAmounts.tsx, src/components/UserIncentiveDistributionList/utils.tsx, src/domain/synthetics/claims/useClaimExecutionFee.ts
---
- https://app.asana.com/0/0/1211557870732425
=> Hotfix: fixed claims for smart contracts
