gmx-io/gmx-interface

- src/Api.js
- src/components/Glp/GlpSwap.js
reviewed & tested.
impacted parts:
- sell GLP works, error message doesn't double
- any contract call should show debug info for not identified error
checked:
- sell GLP works
- in bad case message is not duplicated and correct error is shown
- tested errors with mocked error with compound feature
> fix debug error

- src/components/Exchange/TradeHistory.js
Traders ask why their position was decreased. Rn UI doesn't show that it was decreased by liquidator (or force closed). 
Not sure if "force closed" is the best term, CPC suggested to use "Protected close"
> display force closed action if executed by liquidator

- src/Helpers.js
We were showing converting the error object to string and display in toast. So converting the object returns `[Object object]`. Changed that to display the `e.message`.
> change the helper toast message for Metamask error

- src/views/BuyGMX/BuyGMX.js
Fix the TraderJOE URL to redirect to the trade page with the token already input.
The current link just return to home.
> Fix TraderJOE URL

- src/views/Referrals/Referrals.js
Issue:
- Use referral link with code of tier 2 or 3
- Open /referrals
- You're getting Tier 1
You can try this link https://gmx.io/?ref=Algod with account that **doesn't have code saved onchain**
That reproduces with code from localstorage only, because UI doesn't retrieve owner for that code. And shows default tier 1
cc @xvi10 would be good to merge it soon i guess
@vipineth could you please support that change in `staging`? tell me if there is a better solution to fix this
> fix tier display for code from localstorage

- src/components/Exchange/ConfirmationBox.js
Fix screen getting blank in the situation where:
There is no existing position and user has trigger orders, While using swap screen getting blank with the message in attachement:
> handle no existingOrder for decreaseOrdersThatWillBeExecuted

- src/components/Referrals/AffiliatesStats.js
- src/components/Referrals/referralsHelper.js
- src/domain/common.js
- src/lib/legacy.js
- src/lib/url.ts
[x] Add root url of the domain when we copy the sharable link for referral code
The idea is to make the interface being deployed to any URL in future and not depend on just app.gmx.io. Like few days back `runonflux` team deployed GMX interface on an IFPS and when you copy the sharable link it still goes to `app.gmx.io` it should go to the `runonflux` domain. So now the link copy will depend on the domain origin.
---
- https://app.asana.com/0/0/1203036542861572
> share referral code link based on the root url

- src/App/App.js
- src/components/Exchange/PositionsList.js
- src/lib/legacy.ts
- src/pages/Actions/Actions.js
- src/pages/Exchange/Exchange.css
- src/pages/Exchange/Exchange.js
[x] Show `> 100x` instead of negative leverage numbers when the `Include PnL in leverage display` is unchecked.
---
- https://app.asana.com/0/0/1203668976600222
- https://app.asana.com/0/0/1203777627855630
> change leverage message to >100 x

- src/locales/de/messages.po
- src/locales/en/messages.po
- src/locales/es/messages.po
- src/locales/fr/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/ru/messages.po
- src/locales/zh/messages.po
- src/pages/Stake/StakeV2.js
[x] Update the GLP APR tooltip to include the dune link.
---
- https://app.asana.com/0/0/1204034696950886
> add dune link to glp APR

- src/config/localStorage.ts
- src/config/subgraph.ts
- src/domain/stats/index.ts
- src/domain/stats/types.ts
- src/domain/stats/useFeesSummary.js
- src/domain/stats/useTotalVolume.ts
- src/domain/stats/useVolumeInfo.ts
- src/lib/subgraph/clients.ts
- src/lib/subgraph/utils.ts
- src/pages/Dashboard/DashboardV2.js
**Currently subgraphs don't have hourly data for VolumeStat entities. They should be updated and reindexed before merging this PR**
test subgraphs:
- https://thegraph.com/hosted-service/subgraph/gdev8317/gmx-arbitrum-stats?version=pending
- https://thegraph.com/hosted-service/subgraph/gdev8317/gmx-avalanche-staging?version=pending
after they are fully synced production subgraphs may be updated
---
- https://app.asana.com/0/0/1204042351552672
> use 24h volume from subgraph instead of server endpoint

- src/components/Synthetics/MarketCard/MarketCard.tsx
- src/domain/synthetics/fees/utils/index.ts
- src/locales/de/messages.po
- src/locales/en/messages.po
- src/locales/es/messages.po
- src/locales/fr/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/ru/messages.po
- src/locales/zh/messages.po
fundingRate -> fundingRateShort & fundingRateLong
fundingRateTexts is opposite messages, first message always relates to currently active position type
https://app.asana.com/0/1204313444805313/1205275952944438/f
> add opposite funding rate text in tooltip

- src/components/Synthetics/MarketCard/MarketCard.tsx
- src/config/dataStore.ts
- src/config/events.ts
- src/domain/synthetics/markets/types.ts
- src/domain/synthetics/markets/useMarketsInfo.ts
- src/domain/synthetics/testUtils/mocks.ts
- src/locales/de/messages.po
- src/locales/en/messages.po
- src/locales/es/messages.po
- src/locales/fr/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/ru/messages.po
- src/locales/zh/messages.po
[x] Add adaptive funding rate text to events and on the market card on trade page
---
- https://app.asana.com/0/0/1205743945727419
> add adaptive funding rate text to markets

- public/index.html
That's not obvious why this is a solution for unwanted auto-zoom on mobile devices while focusing input field. But it works good.
Originally viewport's `maximum-scale` property has limited user's ability to zoom-in more then by a specified ratio. But now Apple and Google ignore this property. The only side effect of this property is a disabled auto zoom while user is still capable to zoom the page manually as he wants.
Other possible solutions:
1. Make input's font-size 16px or more (mismatch original design)
2. Keep auto-zoom but let user do pinch actions while modal is open (may cause a problem with absolute positioning)
---
- https://app.asana.com/0/0/1206189396973385
> fix unwanted zoom to focused input

- src/components/Synthetics/ConfirmationBox/ConfirmationBox.tsx
- src/components/Synthetics/OrderEditor/OrderEditor.tsx
- src/components/Synthetics/PositionSeller/PositionSeller.tsx
- src/components/Synthetics/TradeBox/TradeBox.tsx
- src/context/SyntheticsStateContext/selectors/orderEditorSelectors.ts
- src/context/SyntheticsStateContext/selectors/orderSelectors.ts
- src/context/SyntheticsStateContext/selectors/positionSellerSelectors.ts
- src/context/SyntheticsStateContext/selectors/tradeSelectors.ts
- src/context/SyntheticsStateContext/selectors/tradeboxSelectors/index.ts
- src/domain/synthetics/sidecarOrders/useSidecarOrders.ts
The fix is removing `.slice(0, 5)`, i.e. we now check all possible options (40+) instead of just 5.
It takes less than 1ms so that's fine.
The rest of changes are:
- splitting `makeSelectSwapRoutes` into two separate selectors (before selectors it was just one `useMemo` call)
- `makeSelectAllPaths` is now separate selector
---
- https://app.asana.com/0/0/1207370518809255
> fix swap path bug

- src/components/Synthetics/PositionList/PositionList.tsx
- src/context/SyntheticsStateContext/selectors/positionsSelectors.ts
- src/context/SyntheticsStateContext/selectors/tradeboxSelectors/index.ts
1. I attempted to break down usage of [useAvailableTokenOptions](https://github.com/gmx-io/gmx-interface/blob/master/src/domain/synthetics/trade/useAvailableTokenOptions.ts) to separate selectors, but found that it widely used [in building of trade state](https://github.com/gmx-io/gmx-interface/blob/master/src/domain/synthetics/trade/useTradeboxState.ts#L79). Ideal solution seems to in in removing redundant useSomthings which are not making any requests but just mapping the data for building state and replace them by clear selectors, but it requires a massive refactor, so I retreated.
2. Tried to move all positions-specific selectors to a separate file, but it will create a triangle of circular deps, so I didn't change much, just add new file for complex selectors. I opened to discuss and …
> Order positions by available markets, sort descending by Size within the same market

- src/components/Synthetics/GmList/GmList.tsx
- src/locales/de/messages.po
- src/locales/en/messages.po
- src/locales/es/messages.po
- src/locales/fr/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/ru/messages.po
- src/locales/zh/messages.po
Before:
After:
---
- https://app.asana.com/0/0/1207540770484282
> Improve APY tooltip's markup

- src/components/Tooltip/Tooltip.tsx
- src/pages/SyntheticsStats/SyntheticsStats.tsx
first issue was, we rendered all tooltips contents even for hidden ones
initial error was there since release-28
error looks like this:
> fix stats page tooltip

- src/components/TokenSelector/TokenSelector.tsx
- src/components/WithMissedCoinsSearch/WithMissedCoinsSearch.tsx
In v1 we don't have Synthetics Context but TokenSelector is used, which leads to the error “Used useSyntheticsStateSelector outside of SyntheticsStateContextProvider”.
Since calling hooks optionally is dangerous, I put the hook in a special empty component and render it by convention
> missed coins as component

- src/components/Synthetics/GmList/GmList.tsx
- src/components/Synthetics/MarketStats/MarketStatsWithComposition.tsx
- src/components/TokenCard/TokenCard.tsx
- src/domain/synthetics/markets/useGmMarketsApy.ts
- src/domain/synthetics/markets/useMarketTokensData.ts
- src/pages/MarketPoolsPage/MarketPoolsPage.tsx
- src/pages/Stake/StakeV2.tsx
---
- https://app.asana.com/0/0/1208457175023666
> Separated glv token incentives from market token incentives, fixed Buy page max APY displaying

- src/components/MarketSelector/MarketSelector.tsx
- src/components/Synthetics/ChartTokenSelector/ChartTokenSelector.tsx
- src/components/TokenSelector/TokenSelector.tsx
- src/components/UserFeedbackModal/UserFeedbackModal.tsx
- src/components/WithMissedCoinsSearch/WithMissedCoinsSearch.tsx
- src/domain/synthetics/userFeedback/requests.ts
- src/domain/synthetics/userFeedback/useMissedCoinsSearch.ts
- src/domain/synthetics/userFeedback/useNpsSurvey.tsx
- src/lib/metrics/utils.ts
- src/lib/numbers.ts
---
- https://app.asana.com/0/0/1208434922021316
> Improve metric numbers privacy

- src/pages/Dashboard/OverviewCard.tsx
- src/pages/Dashboard/getFormattedFeesDuration.spec.ts
- src/pages/Dashboard/getFormattedFeesDuration.ts
---
- https://app.asana.com/0/0/1208595345585170
> Fees for the past d h not updating if tab is left open
